import {expect,it} from "vitest";
import * as structuralPublic from "../../src/voxel/structural";
import * as canonicalModule from "../../src/voxel/structural/canonical";
import {canonicalAdaptiveJson,hashAdaptiveCanonical,createAdaptiveBrickKey,serializeAdaptiveKey} from "../../src/voxel/adaptive";
import {applyStructuralDestructionCommand,createOwnedStructuralCommandCursor} from "../../src/voxel/structural/commands";
import {serializeStructuralObject,serializeStructuralResult} from "../../src/voxel/structural/canonical";
import {reconstructStructuralObjectInternal,isIssuedStructuralObject,isOwnedStructuralDerivationCandidate,
  ownedStructuralDerivationCandidateSteps,releaseOwnedStructuralDerivationCandidate,createStructuralOwnerLedger} from "../../src/voxel/structural/model";
import {deriveStructuralComponentClassification} from "../../src/voxel/structural/connectivity";
import {structuralOwnedComponentClassificationSteps} from "../../src/voxel/structural/classificationSteps";
import {deriveStructuralObjectMassProperties,structuralOwnedObjectMassSteps} from "../../src/voxel/structural/massProperties";
import {prepareHvpStructuralCommandSourceOwnedSteps} from "../../src/hestia-prototype/physics/structuralPlan";
import {STRUCTURAL_FRAME_BINDING_SCHEMA_VERSION,STRUCTURAL_SOURCE_BINDING_SCHEMA_VERSION,STRUCTURAL_BRICK_SCHEMA_VERSION,
  STRUCTURAL_OBJECT_SCHEMA_VERSION,STRUCTURAL_COMMAND_SCHEMA_VERSION,STRUCTURAL_COMMAND_EVIDENCE_SCHEMA_VERSION,
  STRUCTURAL_RESULT_SCHEMA_VERSION,type StructuralDestructionCommand} from "../../src/voxel/structural/types";

const hash="fnv1a64-v1:0000000000000001";
const frame={schemaVersion:STRUCTURAL_FRAME_BINDING_SCHEMA_VERSION,bodyId:"planet.test",surfaceFrameId:"frame.surface",
  regionId:"region.test",generatorVersion:"generator.v1",objectOriginQuantum:{x:0,y:0,z:0}} as const;
const key=(x:number)=>createAdaptiveBrickKey({bodyId:frame.bodyId,surfaceFrameId:frame.surfaceFrameId,regionId:frame.regionId,
  generatorVersion:frame.generatorVersion,level:4,originQuantum:{x,y:-16,z:16}});
const state=(materialId:number)=>({materialId,partId:null,semanticKey:null,damageKey:null});
const material=(materialId:number)=>({materialId,densityKgPerCubicMeter:512,structuralClass:"wood",destructible:true,tags:null});
const left={schemaVersion:STRUCTURAL_BRICK_SCHEMA_VERSION,key:key(-16),cells:[{localIndex:0,state:state(1)},{localIndex:15,state:state(7)}]};
const right={schemaVersion:STRUCTURAL_BRICK_SCHEMA_VERSION,key:key(0),cells:[{localIndex:0,state:state(256)},{localIndex:1,state:state(65_535)}]};
const sourceBinding={schemaVersion:STRUCTURAL_SOURCE_BINDING_SCHEMA_VERSION,baseFieldIdentity:"base.persistence",baseFieldVersion:"generator.v1",
  baseFieldDescriptorDigest:hash,journalDigest:hash,snapshotProjectionDigest:hash,proofDigests:[hash],sourceRevision:1,editRevision:0,brickRevision:0,planningEpoch:1};
const addressA={brickKey:left.key,local:{x:0,y:0,z:0}},addressB={brickKey:right.key,local:{x:1,y:0,z:0}};
const anchors=[{anchorId:"anchor.a",cell:addressA}];
const joints=[{jointId:"joint.a",jointClass:"weld",endpointA:{cell:addressA,role:"primary"},endpointB:{cell:addressB,role:"secondary"}}];
// Independent literal schema/order oracle from retained preimages7/model + canonical and the
// prior reconstruction-own fixture; no expected value below is generated by the new command core.
const content={schemaVersion:STRUCTURAL_OBJECT_SCHEMA_VERSION,objectId:"object.test",frame,source:sourceBinding,
  materials:[material(1),material(7),material(256),material(65_535)],
  bricks:[{...left,key:serializeAdaptiveKey(left.key)},{...right,key:serializeAdaptiveKey(right.key)}],
  anchors:[{anchorId:"anchor.a",cell:{brickKey:serializeAdaptiveKey(left.key),localIndex:0}}],
  joints:[{jointId:"joint.a",jointClass:"weld",endpointA:{cell:{brickKey:serializeAdaptiveKey(left.key),localIndex:0},role:"primary"},
    endpointB:{cell:{brickKey:serializeAdaptiveKey(right.key),localIndex:1},role:"secondary"}}]};
const budgets={maxVisitedBricks:8,maxVisitedCells:32_768,maxSelectedCells:512,maxChangedCells:512,maxConnectivityCells:32_768,
  maxConnectivityFacts:262_144,maxComponents:32,maxMassCells:32_768};
const box={kind:"box",space:"global-quantum",boundsQuantum:{min:{x:-1,y:-16,z:16},max:{x:1,y:-15,z:17}}} as const;
const base={schemaVersion:STRUCTURAL_COMMAND_SCHEMA_VERSION,commandId:"command.test",targetObjectId:content.objectId,
  expectedObjectRevision:0,resultingObjectRevision:1,expectedAdaptiveSource:sourceBinding,sequence:1,actor:"actor.test",source:"source.test",
  materialFilter:null,budgets};
const resident=8*1024*1024; // All tiny fixture inputs, retained oracles/results and overlapping source references.
type Cursor=ReturnType<typeof createOwnedStructuralCommandCursor>;
const drain=<T>(steps:Generator<unknown,T,unknown>):T=>{
  try{for(;;){const step=steps.next();if(step.done){return step.value;}}}finally{steps.return(undefined as never);}
};
const finish=(cursor:Cursor,units:number)=>{
  let lastPeak=cursor.resources.peakEstimateBytes,lastReserved=cursor.resources.reservedBytes,maxAdvanceUnits=0;
  for(let advance=0;advance<100_000;advance+=1){
    const before=cursor.consumedUnits,step=cursor.advance(units),resource=cursor.resources;
    maxAdvanceUnits=Math.max(maxAdvanceUnits,cursor.consumedUnits-before);
    if(maxAdvanceUnits>units||resource.peakEstimateBytes<lastPeak||(!step.done&&resource.reservedBytes<lastReserved)){
      throw new Error("Non-monotonic/unbounded command progress or aggregate ledger");
    }
    lastPeak=resource.peakEstimateBytes;lastReserved=resource.reservedBytes;
    if(step.done){return {value:step.value,maxAdvanceUnits};}
  }
  throw new Error("Owned command failed to progress");
};
const oracle=(command:unknown,status:"Applied"|"NoChange",bricks:typeof content.bricks,changedKeys:readonly string[],selected:number,changed:number)=>{
  const resultingContent={...content,bricks},previousHash=hashAdaptiveCanonical(content),resultingHash=hashAdaptiveCanonical(resultingContent);
  const receipt={schemaVersion:STRUCTURAL_COMMAND_EVIDENCE_SCHEMA_VERSION,commandId:base.commandId,commandHash:hashAdaptiveCanonical(command),status,
    previousObjectRevision:0,resultingObjectRevision:1,previousEditRevision:0,resultingEditRevision:status==="Applied"?1:0,
    previousContentHash:previousHash,resultingContentHash:resultingHash,changedBrickKeys:changedKeys,selectedVoxelCount:selected,changedVoxelCount:changed,
    adaptiveJournalDigest:hash};
  const object={...resultingContent,objectRevision:1,editRevision:receipt.resultingEditRevision,contentHash:resultingHash,
    commandEvidence:[receipt],evidenceHash:hashAdaptiveCanonical([receipt])};
  const payload={schemaVersion:STRUCTURAL_RESULT_SCHEMA_VERSION,status,commandId:base.commandId,object,changedBrickKeys:changedKeys,
    selectedVoxelCount:selected,changedVoxelCount:changed,invalidations:status==="Applied"?
      ["Components","MassProperties","Mesh"].map(kind=>({kind,sourceObjectRevision:0,sourceContentHash:previousHash})):[]};
  return {...payload,resultHash:hashAdaptiveCanonical(payload)};
};
const checkArray=(values:readonly unknown[])=>{
  expect(Object.getPrototypeOf(values)).toBe(Array.prototype);expect(Object.isFrozen(values)).toBe(true);
  expect(Reflect.ownKeys(values)).toEqual([...Array.from({length:values.length},(_,index)=>String(index)),"length"]);
};

it("keeps retained literal command bytes, generic observations, bounded owner units and one aggregate lifecycle ledger",()=>{
  expect(structuralPublic).not.toHaveProperty("createOwnedStructuralCommandCursor");
  for(const name of ["structuralCanonicalHashSteps","structuralObjectContentHashSteps","structuralEvidenceHashSteps",
    "structuralCommandHashSteps","structuralResultHashSteps"]){
    expect(structuralPublic).not.toHaveProperty(name);
  }
  expect(structuralPublic).toHaveProperty("applyStructuralDestructionCommand");
  expect(structuralPublic.applyStructuralDestructionCommand).toBe(applyStructuralDestructionCommand);
  for(const name of ["projectStructuralObjectContent","projectStructuralCommandEvidence","projectStructuralObject","projectStructuralResult",
    "canonicalStructuralJson","serializeStructuralCellAddress","serializeStructuralObject","serializeStructuralCommand","serializeStructuralResult",
    "hashStructuralObjectContent","hashStructuralEvidence","hashStructuralCommand","hashStructuralResult","hashStructuralAdaptiveAuthorityBinding",
    "hashStructuralComponentId","hashStructuralFragmentContent","hashStructuralFragmentId"] as const){
    expect(structuralPublic).toHaveProperty(name);
    expect(structuralPublic[name]).toBe(canonicalModule[name]);
  }
  const source=reconstructStructuralObjectInternal({objectId:content.objectId,frame,source:sourceBinding,
    materials:[material(65_535),material(1),material(256),material(7)],bricks:[right,left],anchors,joints,
    objectRevision:0,editRevision:0,commandEvidence:[]});
  expect(source.contentHash).toBe(hashAdaptiveCanonical(content));
  const before=serializeStructuralObject(source);
  const subtract={...base,kind:"SubtractBox",shape:box};
  const sphere={...base,kind:"SubtractSphere",shape:{kind:"sphere",space:"global-quantum",centerQuantum:{x:-15,y:-15,z:17},radiusQuantum:1}};
  const set={...base,kind:"SetMaterialBox",shape:box,materialId:65_535};
  const noChange={...set,shape:{...box,boundsQuantum:{min:{x:1,y:-16,z:16},max:{x:2,y:-15,z:17}}}};
  const cases=[
    {command:subtract,expected:oracle(subtract,"Applied",[{...content.bricks[0]!,cells:[left.cells[0]!]},{...content.bricks[1]!,cells:[right.cells[1]!]}],content.bricks.map(brick=>brick.key),2,2)},
    {command:sphere,expected:oracle(sphere,"Applied",[{...content.bricks[0]!,cells:[left.cells[1]!]},content.bricks[1]!],[content.bricks[0]!.key],1,1)},
    {command:set,expected:oracle(set,"Applied",[{...content.bricks[0]!,cells:[left.cells[0]!,{localIndex:15,state:state(65_535)}]},
      {...content.bricks[1]!,cells:[{localIndex:0,state:state(65_535)},right.cells[1]!]}],content.bricks.map(brick=>brick.key),2,2)},
    {command:noChange,expected:oracle(noChange,"NoChange",content.bricks,[],1,0)}
  ];
  const records:unknown[]=[];
  let baselineUnits=0,peak=0;
  for(const units of [1,7,16,32,64,257]){
    for(const fixture of cases){
      const commandBefore=canonicalAdaptiveJson(fixture.command),generic=applyStructuralDestructionCommand(source,fixture.command);
      const cursor=createOwnedStructuralCommandCursor(source,fixture.command,resident),result=finish(cursor,units);
      expect(JSON.parse(serializeStructuralResult(generic))).toEqual(fixture.expected);
      expect(JSON.parse(serializeStructuralResult(result.value))).toEqual(fixture.expected);
      expect(result.value).toEqual(generic);expect(cursor.resources.reservedBytes).toBe(0);expect(cursor.resources.retainedEstimateBytes).toBe(0);
      expect(cursor.resources.hashReservations).toBeGreaterThan(5);expect(cursor.resources.transferredResultEstimateBytes).toBeGreaterThan(0);
      peak=Math.max(peak,cursor.resources.peakEstimateBytes);if(units===1&&fixture.command===subtract){baselineUnits=cursor.consumedUnits;}
      const retained=serializeStructuralResult(result.value);expect(()=>cursor.advance(1)).toThrow("once-only");cursor.dispose();cursor.dispose();
      expect(serializeStructuralResult(result.value)).toBe(retained);expect(canonicalAdaptiveJson(fixture.command)).toBe(commandBefore);
      expect(isIssuedStructuralObject(result.value.object)).toBe(true);checkArray(result.value.object.bricks);checkArray(result.value.object.materials);
      checkArray(result.value.object.source.proofDigests);checkArray(result.value.object.commandEvidence);
      for(const brick of result.value.object.bricks){checkArray(brick.cells);}
      if(result.value.status!=="Rejected"){checkArray(result.value.changedBrickKeys);checkArray(result.value.invalidations);}
      records.push({units,kind:fixture.command.kind,status:result.value.status,wholeUnits:cursor.consumedUnits,maxAdvanceUnits:result.maxAdvanceUnits,
        resultHash:result.value.resultHash,peakEstimateBytes:cursor.resources.peakEstimateBytes});
    }
  }
  const rejectedCases=[
    {...subtract,expectedObjectRevision:1,resultingObjectRevision:2},
    {...subtract,kind:"unknown",sequence:1,tick:1},
    {...subtract,budgets:{...budgets,maxMassCells:1}},
    {...subtract,budgets:{...budgets,maxComponents:1}},
    {...subtract,materialFilter:{materialIds:[65_535,256]}}
  ];
  for(const command of rejectedCases){
    const generic=applyStructuralDestructionCommand(source,command),cursor=createOwnedStructuralCommandCursor(source,command,resident);
    const owned=finish(cursor,7).value;expect(owned).toEqual(generic);expect(owned.status).toBe("Rejected");expect(cursor.resources.reservedBytes).toBe(0);cursor.dispose();
  }
  // Every source field participates, including the FULL proof array (not a cached/subset digest).
  for(const [field,value] of Object.entries(sourceBinding)){
    const replacement=field==="proofDigests"?["fnv1a64-v1:0000000000000002"]:typeof value==="number"?value+1:
      field.endsWith("Digest")?"fnv1a64-v1:0000000000000002":`${String(value)}.changed`;
    const command={...subtract,expectedAdaptiveSource:{...sourceBinding,[field]:replacement}};
    const generic=applyStructuralDestructionCommand(source,command),cursor=createOwnedStructuralCommandCursor(source,command,resident);
    expect(finish(cursor,16).value).toEqual(generic);expect(generic.status).toBe("Rejected");expect(cursor.resources.reservedBytes).toBe(0);cursor.dispose();
  }
  const reads:string[]=[];
  const proofs=Object.freeze(Array.from({length:4096},(_,index)=>`fnv1a64-v1:${index.toString(16).padStart(16,"0")}`));
  const largeSource=reconstructStructuralObjectInternal({objectId:source.objectId,frame:source.frame,source:{...source.source,proofDigests:proofs},
    materials:source.materials,bricks:source.bricks,anchors:source.anchors,joints:source.joints,objectRevision:0,editRevision:0,commandEvidence:[]});
  const largeCommand={...subtract,expectedAdaptiveSource:largeSource.source,materialFilter:{materialIds:Object.freeze(Array.from({length:4096},(_,index)=>index+1))}};
  const largeCursor=createOwnedStructuralCommandCursor(largeSource,largeCommand,resident),largeResult=finish(largeCursor,257).value;
  expect(largeResult).toEqual(applyStructuralDestructionCommand(largeSource,largeCommand));expect(largeCursor.resources.reservedBytes).toBe(0);
  const largeResources=largeCursor.resources;largeCursor.dispose();
  const observed={get kind(){reads.push("kind");return "SubtractBox";},get sequence(){reads.push("sequence");return 1;},get tick(){reads.push("tick");return 1;}};
  expect(applyStructuralDestructionCommand(source,observed)).toMatchObject({status:"Rejected",path:"command/kind",code:"InvalidContract"});
  expect(reads).toEqual([]); // Original plain-record contract rejects accessors without invoking them.
  const proxy=new Proxy({kind:"SubtractBox",sequence:1,tick:1},{
    get(target,property,receiver){reads.push(`get:${String(property)}`);return Reflect.get(target,property,receiver);},
    getOwnPropertyDescriptor(target,property){reads.push(`descriptor:${String(property)}`);return Reflect.getOwnPropertyDescriptor(target,property);}
  });
  expect(applyStructuralDestructionCommand(source,proxy)).toMatchObject({status:"Rejected",path:"command",code:"InvalidContract"});
  expect(reads).toEqual(["descriptor:commandId","descriptor:kind","descriptor:sequence","descriptor:tick",
    "get:kind","descriptor:sequence","descriptor:tick"]);
  const ledger=createStructuralOwnerLedger(resident),preliminary=drain(ownedStructuralDerivationCandidateSteps(source,source.bricks,1,0,ledger.reserve));
  expect(isIssuedStructuralObject(preliminary)).toBe(false);expect(isOwnedStructuralDerivationCandidate(preliminary)).toBe(true);
  const connectivity={maxVisitedCells:32_768,maxIndexedFacts:262_144,maxComponents:32};
  expect(drain(structuralOwnedComponentClassificationSteps(preliminary,connectivity,ledger.reserve))).toEqual(deriveStructuralComponentClassification(preliminary,connectivity));
  const afterClassification=ledger.resources.reservedBytes;
  const ownedMass=drain(structuralOwnedObjectMassSteps(preliminary,{maxVisitedCells:32_768},ledger.reserve));
  expect(ownedMass).toEqual(deriveStructuralObjectMassProperties(preliminary,{maxVisitedCells:32_768}));
  expect(ownedMass.totalMassKg).toBe(4);expect(ledger.resources.reservedBytes).toBeGreaterThan(afterClassification);
  releaseOwnedStructuralDerivationCandidate(preliminary);expect(isOwnedStructuralDerivationCandidate(preliminary)).toBe(false);
  expect(()=>drain(structuralOwnedObjectMassSteps(preliminary,{maxVisitedCells:32_768},ledger.reserve))).toThrow("Owned mass requires");
  ledger.release();expect(ledger.resources.reservedBytes).toBe(0);expect(ledger.resources.retainedEstimateBytes).toBe(0);
  const tight=createOwnedStructuralCommandCursor(source,subtract,resident,20_000);let first:unknown;
  try{finish(tight,1);}catch(error){first=error;}
  expect(first).toMatchObject({code:"InvalidBudget",path:"cursor/prepareBytes"});expect(tight.resources.reservedBytes).toBe(0);
  try{tight.advance(257);}catch(error){expect(error).toBe(first);}tight.dispose();tight.dispose();try{tight.advance(1);}catch(error){expect(error).toBe(first);}
  expect(finish(createOwnedStructuralCommandCursor(source,subtract,resident),64).value.status).toBe("Applied");
  const boundaries=[0,1,7,16,32,64,257,Math.floor(baselineUnits/4),Math.floor(baselineUnits/2),baselineUnits-1];
  for(const boundary of boundaries){
    const canceled=createOwnedStructuralCommandCursor(source,subtract,resident);
    if(boundary>0){expect(canceled.advance(boundary).done).toBe(false);}canceled.dispose();canceled.dispose();
    expect(canceled.resources.reservedBytes).toBe(0);expect(canceled.resources.retainedEstimateBytes).toBe(0);
    const host=createOwnedStructuralCommandCursor(source,subtract,resident);
    try{if(boundary>0){host.advance(boundary);}throw new Error("host sentinel");}catch(error){expect((error as Error).message).toBe("host sentinel");}finally{host.dispose();}
    expect(host.resources.reservedBytes).toBe(0);
    const invalid=createOwnedStructuralCommandCursor(source,subtract,resident);
    if(boundary>0){invalid.advance(boundary);}let failure:unknown;try{invalid.advance(0);}catch(error){failure=error;}
    expect(failure).toMatchObject({code:"InvalidBudget",path:"cursor/maxUnits"});expect(invalid.resources.reservedBytes).toBe(0);invalid.dispose();
    try{invalid.advance(1);}catch(error){expect(error).toBe(failure);}
  }
  const moduleResult=drain(prepareHvpStructuralCommandSourceOwnedSteps(source,subtract as unknown as StructuralDestructionCommand,resident));
  expect(moduleResult).toEqual(applyStructuralDestructionCommand(source,subtract));expect(serializeStructuralObject(source)).toBe(before);
  console.log("OWNED_COMMAND_CURSOR_EVIDENCE",JSON.stringify({cases:records,cancelBoundaries:boundaries.length,hostFinallyBoundaries:boundaries.length,
    invalidBudgetBoundaries:boundaries.length,wholeSingleUnitResumptions:baselineUnits,peakEstimateBytes:peak,finalReservations:0,
    proofAndFilter4096:{wholeUnits:largeCursor.consumedUnits,resources:largeResources},
    preliminaryFinalIssued:false,producerArrays:"plain index-only locked; inputs unchanged",physicalHeap:"NOT_PROVEN",whole8ms:"NOT_PROVEN",productionActivation:"OFF"}));
});
