import { expect, test, type Page } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const evidenceDir = path.resolve(process.cwd(), "evidence");
const summaryPath = path.join(evidenceDir, "browser-celestial-gravity-core-v1-summary.json");
const markdownPath = path.join(evidenceDir, "browser-celestial-gravity-core-v1.md");
const generator = "apps/weltraum-browser/tests/e2e/celestial-gravity-core.spec.ts";
const focusedCommand = "npm run test:e2e -- tests/e2e/celestial-gravity-core.spec.ts";

interface NormalPageGuard {
  readonly route: string;
  readonly testBridgeOwnProperty: boolean;
  readonly testBridgeInWindow: boolean;
  readonly bodyContainsTestBridge: boolean;
  readonly debugHudVisible: boolean;
}

interface CelestialBrowserRun {
  readonly modulePath: string;
  readonly importedPublicApi: readonly string[];
  readonly catalogId: string;
  readonly catalogSignature: string;
  readonly bodyIds: readonly string[];
  readonly rootBodyId: string;
  readonly epochSeconds: number;
  readonly requestedTimeSeconds: number;
  readonly secondRequestedTimeSeconds: number;
  readonly ephemerisSignature: string;
  readonly secondEphemerisSignature: string;
  readonly rootPositionMeters: { readonly x: number; readonly y: number; readonly z: number };
  readonly moonParentFrame: string | undefined;
  readonly moonAbsoluteFrame: string;
  readonly surfaceGravityMetersPerSecondSquared: number;
  readonly escapeVelocityMetersPerSecond: number;
  readonly dominantSourceBodyId: string;
  readonly canonicalResult: string;
  readonly suiteSignature: string;
}

interface CelestialEvidence {
  readonly schemaVersion: "browser-celestial-gravity-core-v1";
  readonly generator: string;
  readonly test: string;
  readonly normalPageGuard: NormalPageGuard;
  readonly browserHealth: {
    readonly consoleErrors: readonly string[];
    readonly ignoredKnownBrowserNoiseRule: "only the normal page favicon.ico HTTP 404 console message";
    readonly pageErrors: readonly string[];
    readonly failedRequests: readonly string[];
    readonly errorResponses: readonly string[];
  };
  readonly dynamicImport: {
    readonly modulePath: string;
    readonly importedPublicApi: readonly string[];
  };
  readonly deterministicRepeat: {
    readonly identicalCanonicalResult: boolean;
    readonly identicalSuiteSignature: boolean;
    readonly catalogSignature: string;
    readonly ephemerisSignature: string;
    readonly secondEphemerisSignature: string;
    readonly suiteSignature: string;
  };
  readonly starterSystem: {
    readonly catalogId: string;
    readonly rootBodyId: string;
    readonly bodyIds: readonly string[];
  };
  readonly explicitTime: {
    readonly epochSeconds: number;
    readonly requestedTimeSeconds: number;
    readonly secondRequestedTimeSeconds: number;
  };
  readonly frameAndGravityProbe: {
    readonly rootPositionMeters: { readonly x: number; readonly y: number; readonly z: number };
    readonly moonParentFrame: string | undefined;
    readonly moonAbsoluteFrame: string;
    readonly surfaceGravityMetersPerSecondSquared: number;
    readonly escapeVelocityMetersPerSecond: number;
    readonly dominantSourceBodyId: string;
  };
  readonly scope: readonly string[];
  readonly nonGoals: readonly string[];
  readonly verification: {
    readonly command: string;
    readonly expectedResult: string;
    readonly observedResult: "pass";
    readonly screenshot: "not captured: no visual change";
  };
}

const expectNormalPageGuard = async (page: Page): Promise<NormalPageGuard> => {
  await page.goto("/");
  await page.waitForSelector("#debug-scene", { state: "visible" });
  await expect.poll(() => page.evaluate(() => Object.prototype.hasOwnProperty.call(window, "TestBridge"))).toBe(false);
  await expect.poll(() => page.evaluate(() => "TestBridge" in window)).toBe(false);
  await expect(page.locator("body")).not.toContainText("TestBridge");
  await expect(page.locator("#debug-hud")).toBeHidden();

  const guard = await page.evaluate(() => ({
    route: location.pathname,
    testBridgeOwnProperty: Object.prototype.hasOwnProperty.call(window, "TestBridge"),
    testBridgeInWindow: "TestBridge" in window,
    bodyContainsTestBridge: (document.body.textContent ?? "").includes("TestBridge"),
    debugHudVisible: document.querySelector<HTMLElement>("#debug-hud")?.offsetParent !== null
  }));
  expect(guard).toEqual({
    route: "/",
    testBridgeOwnProperty: false,
    testBridgeInWindow: false,
    bodyContainsTestBridge: false,
    debugHudVisible: false
  });
  return guard;
};

const createMarkdown = (evidence: CelestialEvidence): string => `# Browser Celestial Gravity Core v1 Evidence

Generated by \`${evidence.generator}\`.

## Normal Browser Page

- Route: \`${evidence.normalPageGuard.route}\`
- TestBridge present: \`${evidence.normalPageGuard.testBridgeInWindow}\`
- Debug HUD visible: \`${evidence.normalPageGuard.debugHudVisible}\`
- Console errors: \`${evidence.browserHealth.consoleErrors.length}\`
- Ignored known browser noise rule: \`${evidence.browserHealth.ignoredKnownBrowserNoiseRule}\`
- Page errors: \`${evidence.browserHealth.pageErrors.length}\`
- Failed requests: \`${evidence.browserHealth.failedRequests.length}\`
- HTTP error responses: \`${evidence.browserHealth.errorResponses.length}\`

## Public Module And Determinism

- Dynamic import: \`${evidence.dynamicImport.modulePath}\`
- Public API exercised: ${evidence.dynamicImport.importedPublicApi.map((name) => `\`${name}\``).join(", ")}
- Repeated canonical result identical: \`${evidence.deterministicRepeat.identicalCanonicalResult}\`
- Repeated suite signature identical: \`${evidence.deterministicRepeat.identicalSuiteSignature}\`
- Catalog signature: \`${evidence.deterministicRepeat.catalogSignature}\`
- Ephemeris signature: \`${evidence.deterministicRepeat.ephemerisSignature}\`
- Second-time ephemeris signature: \`${evidence.deterministicRepeat.secondEphemerisSignature}\`
- Suite signature: \`${evidence.deterministicRepeat.suiteSignature}\`

## Starter System

- Catalog: \`${evidence.starterSystem.catalogId}\`
- Root: \`${evidence.starterSystem.rootBodyId}\`
- Bodies (${evidence.starterSystem.bodyIds.length}): ${evidence.starterSystem.bodyIds.map((id) => `\`${id}\``).join(", ")}
- Explicit epoch/requested times: \`${evidence.explicitTime.epochSeconds}\` / \`${evidence.explicitTime.requestedTimeSeconds}\` and \`${evidence.explicitTime.secondRequestedTimeSeconds}\` seconds
- Moon parent frame: \`${evidence.frameAndGravityProbe.moonParentFrame}\`
- Moon absolute frame: \`${evidence.frameAndGravityProbe.moonAbsoluteFrame}\`
- Dominant source at the Hestia surface probe: \`${evidence.frameAndGravityProbe.dominantSourceBodyId}\`
- Surface gravity: \`${evidence.frameAndGravityProbe.surfaceGravityMetersPerSecondSquared}\` m/s^2
- Escape velocity: \`${evidence.frameAndGravityProbe.escapeVelocityMetersPerSecond}\` m/s

## Scope

${evidence.scope.map((item) => `- ${item}`).join("\n")}

### Deferred

${evidence.nonGoals.map((item) => `- ${item}`).join("\n")}

## Focused Verification

- Command: \`${evidence.verification.command}\`
- Expected: ${evidence.verification.expectedResult}
- Observed: ${evidence.verification.observedResult}
- Screenshot: ${evidence.verification.screenshot}
`;

test("normal page imports and proves the deterministic celestial and gravity core", async ({ page }) => {
  const consoleErrors: string[] = [];
  const ignoredKnownBrowserNoise: string[] = [];
  const pageErrors: string[] = [];
  const failedRequests: string[] = [];
  const errorResponses: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error") {
      const location = message.location();
      const entry = `${message.text()}${location.url ? ` [${location.url}]` : ""}`;
      if (location.url.endsWith("/favicon.ico") && message.text().includes("404")) {
        ignoredKnownBrowserNoise.push(entry);
      } else {
        consoleErrors.push(entry);
      }
    }
  });
  page.on("pageerror", (error) => pageErrors.push(error.message));
  page.on("requestfailed", (request) => failedRequests.push(`${request.method()} ${request.url()}`));
  page.on("response", (response) => {
    if (response.status() >= 400) errorResponses.push(`${response.status()} ${response.url()}`);
  });

  const normalPageGuard = await expectNormalPageGuard(page);
  const repeated = await page.evaluate(async (): Promise<{ readonly first: CelestialBrowserRun; readonly second: CelestialBrowserRun }> => {
    const modulePath = "/src/celestial/index.ts";
    const celestial = await import(modulePath);
    const importedPublicApi = [
      "createStarterCelestialCatalog",
      "computeCatalogEphemeris",
      "gravitySourceFromRuntimeState",
      "gravityAccelerationAtPosition",
      "selectDominantGravitySource",
      "surfaceGravity",
      "escapeVelocity",
      "canonicalCelestialJson",
      "celestialSignature"
    ];

    const run = (): CelestialBrowserRun => {
      const catalog = celestial.createStarterCelestialCatalog();
      const epochSeconds = 12_000;
      const requestedTimeSeconds = 345_678;
      const secondRequestedTimeSeconds = requestedTimeSeconds + celestial.DAY_SECONDS;
      const ephemeris = celestial.computeCatalogEphemeris(catalog, { epochSeconds, requestedTimeSeconds });
      const secondEphemeris = celestial.computeCatalogEphemeris(catalog, {
        epochSeconds,
        requestedTimeSeconds: secondRequestedTimeSeconds
      });
      const star = catalog.indexes.bodyById[celestial.STARTER_BODY_IDS.aurelia];
      const hestia = catalog.indexes.bodyById[celestial.STARTER_BODY_IDS.hestia];
      const starState = ephemeris.stateByBodyId[star.bodyId];
      const hestiaState = ephemeris.stateByBodyId[hestia.bodyId];
      const moonState = ephemeris.stateByBodyId[celestial.STARTER_BODY_IDS.luma];
      const starSource = celestial.gravitySourceFromRuntimeState(star, starState);
      const hestiaSource = celestial.gravitySourceFromRuntimeState(hestia, hestiaState);
      const surfaceProbe = {
        x: hestiaState.absoluteState.positionMeters.x + hestia.radiusMeters,
        y: hestiaState.absoluteState.positionMeters.y,
        z: hestiaState.absoluteState.positionMeters.z
      };
      const surfaceGravity = celestial.gravityAccelerationAtPosition(hestiaSource, surfaceProbe);
      const dominant = celestial.selectDominantGravitySource([starSource, hestiaSource], surfaceProbe);
      const payload = {
        modulePath,
        importedPublicApi,
        catalogId: catalog.catalogId,
        catalogSignature: catalog.signature,
        bodyIds: catalog.bodies.map((body: { readonly bodyId: string }) => body.bodyId),
        rootBodyId: catalog.rootBodyId,
        epochSeconds,
        requestedTimeSeconds,
        secondRequestedTimeSeconds,
        ephemerisSignature: ephemeris.signature,
        secondEphemerisSignature: secondEphemeris.signature,
        rootPositionMeters: starState.absoluteState.positionMeters,
        moonParentFrame: moonState.parentRelativeState?.frame.referenceBodyId,
        moonAbsoluteFrame: moonState.absoluteState.frame.referenceBodyId,
        surfaceGravityMetersPerSecondSquared: surfaceGravity.magnitudeMetersPerSecondSquared,
        escapeVelocityMetersPerSecond: celestial.escapeVelocity(hestia),
        dominantSourceBodyId: dominant.source.bodyId
      };
      return {
        ...payload,
        canonicalResult: celestial.canonicalCelestialJson(payload),
        suiteSignature: celestial.celestialSignature(payload)
      };
    };

    return { first: run(), second: run() };
  });

  expect(repeated.first.importedPublicApi.every((name) => name.length > 0)).toBe(true);
  expect(repeated.first.bodyIds).toHaveLength(15);
  expect(repeated.first.rootBodyId).toBe("star.aurelia");
  expect(repeated.first.rootPositionMeters).toEqual({ x: 0, y: 0, z: 0 });
  expect(repeated.first.moonParentFrame).toBe("planet.hestia");
  expect(repeated.first.moonAbsoluteFrame).toBe("star.aurelia");
  expect(repeated.first.dominantSourceBodyId).toBe("planet.hestia");
  expect(repeated.first.surfaceGravityMetersPerSecondSquared).toBeGreaterThan(0);
  expect(repeated.first.escapeVelocityMetersPerSecond).toBeGreaterThan(0);
  expect(repeated.first.secondEphemerisSignature).not.toBe(repeated.first.ephemerisSignature);
  expect(repeated.first.canonicalResult).toBe(repeated.second.canonicalResult);
  expect(repeated.first.suiteSignature).toBe(repeated.second.suiteSignature);
  expect(errorResponses).toEqual([]);
  expect(failedRequests).toEqual([]);
  expect(pageErrors).toEqual([]);
  expect(consoleErrors).toEqual([]);
  expect(ignoredKnownBrowserNoise.every((entry) => entry.includes("/favicon.ico") && entry.includes("404"))).toBe(true);

  const evidence: CelestialEvidence = {
    schemaVersion: "browser-celestial-gravity-core-v1",
    generator,
    test: "normal page imports and proves the deterministic celestial and gravity core",
    normalPageGuard,
    browserHealth: {
      consoleErrors,
      ignoredKnownBrowserNoiseRule: "only the normal page favicon.ico HTTP 404 console message",
      pageErrors,
      failedRequests,
      errorResponses
    },
    dynamicImport: {
      modulePath: repeated.first.modulePath,
      importedPublicApi: repeated.first.importedPublicApi
    },
    deterministicRepeat: {
      identicalCanonicalResult: repeated.first.canonicalResult === repeated.second.canonicalResult,
      identicalSuiteSignature: repeated.first.suiteSignature === repeated.second.suiteSignature,
      catalogSignature: repeated.first.catalogSignature,
      ephemerisSignature: repeated.first.ephemerisSignature,
      secondEphemerisSignature: repeated.first.secondEphemerisSignature,
      suiteSignature: repeated.first.suiteSignature
    },
    starterSystem: {
      catalogId: repeated.first.catalogId,
      rootBodyId: repeated.first.rootBodyId,
      bodyIds: repeated.first.bodyIds
    },
    explicitTime: {
      epochSeconds: repeated.first.epochSeconds,
      requestedTimeSeconds: repeated.first.requestedTimeSeconds,
      secondRequestedTimeSeconds: repeated.first.secondRequestedTimeSeconds
    },
    frameAndGravityProbe: {
      rootPositionMeters: repeated.first.rootPositionMeters,
      moonParentFrame: repeated.first.moonParentFrame,
      moonAbsoluteFrame: repeated.first.moonAbsoluteFrame,
      surfaceGravityMetersPerSecondSquared: repeated.first.surfaceGravityMetersPerSecondSquared,
      escapeVelocityMetersPerSecond: repeated.first.escapeVelocityMetersPerSecond,
      dominantSourceBodyId: repeated.first.dominantSourceBodyId
    },
    scope: [
      "Normal / startup with TestBridge absent and debug HUD hidden.",
      "In-page dynamic import of /src/celestial/index.ts.",
      "Explicit-time starter catalog ephemeris, frame composition, local gravity, and deterministic repeat proof."
    ],
    nonGoals: [
      "No renderer, runtime, navigation, flight, UI, world, or Unity integration.",
      "No N-body, SOI, collision, landing, atmosphere simulation, stations, or unnamed bodies.",
      "No screenshot because this change has no visible UI or scene effect."
    ],
    verification: {
      command: focusedCommand,
      expectedResult: "one focused Playwright test passes and writes both task-owned evidence files",
      observedResult: "pass",
      screenshot: "not captured: no visual change"
    }
  };

  await mkdir(evidenceDir, { recursive: true });
  await writeFile(summaryPath, `${JSON.stringify(evidence, null, 2)}\n`, "utf8");
  await writeFile(markdownPath, createMarkdown(evidence), "utf8");
});
