import { expect, test, type Page } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const evidenceDir = path.resolve(process.cwd(), "evidence");

interface ObjectiveEvidence {
  readonly phase: string;
  readonly label: string;
  readonly status: string;
  readonly target: string;
  readonly distanceDisplay: string;
  readonly distanceMeters: number;
  readonly nextAction: string;
  readonly hint: string;
}

const distanceFromHud = (text: string): number => {
  const match = text.match(/([\d.]+)\s*(km|m)\b/);
  if (!match) {
    throw new Error(`Missing HUD distance in m or km: ${text}`);
  }
  const value = Number(match[1]);
  return match[2] === "km" ? value * 1000 : value;
};

async function expectTestBridgeHidden(page: Page): Promise<void> {
  await expect.poll(() => page.evaluate(() => "TestBridge" in window)).toBe(false);
  await expect(page.getByTestId("basic-hud")).not.toContainText("TestBridge");
}

async function selectVisiblePlannerTarget(page: Page, targetId: string, label: string): Promise<string> {
  await expect(page.locator("#open-navigation-planner")).toBeVisible();
  await page.locator("#open-navigation-planner").click();
  const planner = page.getByTestId("navigation-planner");
  await expect(planner).toBeVisible();
  const target = page.locator(`#planner-target-options button[data-planner-target-id="${targetId}"]`);
  await expect(target).toBeVisible();
  await target.click();
  await expect(target).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByTestId("planner-selected-target")).toContainText(label);
  await expect(page.getByTestId("planner-objective")).toContainText("Reach Range 500m");
  await expect.poll(async () => (await planner.getAttribute("data-visible-preview-hash")) ?? "").toMatch(/^[a-f0-9]{8}$/);
  const previewHash = (await planner.getAttribute("data-visible-preview-hash"))!;
  await expect(page.locator("#planner-route-detail")).toContainText(previewHash);
  await page.locator("#planner-close").click();
  return previewHash;
}

async function engageVisiblePreview(page: Page, expectedHash: string): Promise<void> {
  await page.locator("#open-navigation-planner").click();
  await expect(page.getByTestId("navigation-planner")).toHaveAttribute("data-visible-preview-hash", expectedHash);
  await expect(page.getByTestId("planner-engage-route")).toBeEnabled();
  await page.getByTestId("planner-engage-route").click();
  await expect(page.getByTestId("navigation-planner")).toBeHidden();
}

async function readObjectiveEvidence(page: Page, phase: string): Promise<ObjectiveEvidence> {
  const distanceDisplay = await page.getByTestId("objective-distance").innerText();
  return {
    phase,
    label: await page.getByTestId("objective-label").innerText(),
    status: await page.getByTestId("objective-status").innerText(),
    target: await page.getByTestId("objective-target").innerText(),
    distanceDisplay,
    distanceMeters: distanceFromHud(distanceDisplay),
    nextAction: await page.getByTestId("objective-next-action").innerText(),
    hint: await page.getByTestId("objective-hint").innerText()
  };
}

async function waitForRuntimeFrames(page: Page, frameCount: number): Promise<void> {
  await page.evaluate(async (frames) => {
    for (let index = 0; index < frames; index += 1) {
      await new Promise<void>((resolve) => requestAnimationFrame(() => resolve()));
    }
  }, frameCount);
}

async function waitForObjectiveComplete(page: Page, readyDistanceMeters: number): Promise<ObjectiveEvidence> {
  const deadline = Date.now() + 60_000;
  let latest = await readObjectiveEvidence(page, "complete-or-progress");
  let progressed = latest.distanceMeters < readyDistanceMeters - 2;

  while (Date.now() < deadline) {
    await waitForRuntimeFrames(page, 60);
    await page.waitForTimeout(500);
    latest = await readObjectiveEvidence(page, "complete-or-progress");
    progressed = progressed || latest.distanceMeters < readyDistanceMeters - 2;
    if (latest.status === "Complete") {
      return latest;
    }
  }

  expect(progressed, "Objective should at least show live distance progress before the completion wait budget ends").toBe(true);
  return latest;
}

function createMarkdown(rows: readonly ObjectiveEvidence[]): string {
  const tableRows = rows
    .map((row) => `| ${row.phase} | ${row.label} | ${row.status} | ${row.target} | ${row.distanceDisplay} | ${row.distanceMeters} | ${row.nextAction} | ${row.hint} |`)
    .join("\n");

  return `# Browser Large-Field Navigation Objective v1 Evidence

Generated by \`apps/weltraum-browser/tests/e2e/large-field-navigation-objective.spec.ts\` against the normal product URL \`/\`.

## Objective Runtime Results

| Phase | Objective | Status | Target | HUD distance | Parsed distance (m) | Next action | Hint |
| --- | --- | --- | --- | --- | ---: | --- | --- |
${tableRows}

## Screenshots

- \`apps/weltraum-browser/evidence/large-field-objective-ready.png\`
- \`apps/weltraum-browser/evidence/large-field-objective-enroute.png\`
- \`apps/weltraum-browser/evidence/large-field-objective-complete-or-progress.png\`

## Guardrails

- Default \`/\` kept \`window.TestBridge\` absent.
- Demo Scout GLB loaded through the normal runtime.
- Objective target focus, route preview, and autopilot Engage used the visible navigation planner.
- Objective progress was observed from player HUD distance/status, not renderer-only markers or TestBridge helpers.
`;
}

test("normal runtime presents and progresses the Range 500m navigation objective", async ({ page }) => {
  test.setTimeout(95_000);
  await mkdir(evidenceDir, { recursive: true });
  await page.goto("/");
  await page.waitForSelector("#debug-scene", { state: "visible" });
  await expectTestBridgeHidden(page);
  await expect(page.getByTestId("ship-visual-source")).toContainText("Ship visual: Demo Scout GLB", { timeout: 20_000 });

  await expect(page.getByTestId("objective-label")).toContainText("Reach Range 500m");
  await expect(page.getByTestId("objective-label")).toBeVisible();
  await expect(page.getByTestId("objective-status")).toContainText("Available");
  await expect(page.getByTestId("objective-status")).toBeVisible();
  await expect(page.getByTestId("objective-distance")).toBeVisible();
  await expect(page.getByTestId("objective-target")).toContainText("Range 500m");
  await expect(page.getByTestId("objective-next-action")).toContainText("select target");
  await expect(page.getByTestId("objective-options")).toBeHidden();

  const previewHash = await selectVisiblePlannerTarget(page, "range-500m", "Range 500m");
  await expect(page.getByTestId("selected-target")).toContainText("Range 500m");
  await expect(page.locator("#route-status")).toContainText(/preview ready/i);
  await expect(page.getByTestId("objective-status")).toContainText("Route ready");
  await expect(page.getByTestId("objective-next-action")).toContainText("engage autopilot");
  await expect(page.getByTestId("objective-hint")).toContainText("engage autopilot");
  const ready = await readObjectiveEvidence(page, "ready");
  const readyScreenshot = await page.screenshot({ fullPage: true });

  await engageVisiblePreview(page, previewHash);
  await expect(page.getByTestId("autopilot-active")).toContainText("Autopilot executing");
  await expect(page.getByTestId("objective-status")).toContainText(/Enroute|Complete/);
  const enroute = await readObjectiveEvidence(page, "enroute");
  const enrouteScreenshot = await page.screenshot({ fullPage: true });

  const progress = await waitForObjectiveComplete(page, ready.distanceMeters);
  expect(progress.distanceMeters).toBeLessThan(ready.distanceMeters);
  expect(progress.status).toBe("Complete");
  expect(progress.nextAction).toBe("next objective available");
  expect(progress.hint).toContain("complete");
  expect(progress.hint).toContain("Reach Range 1000m is available");
  const progressScreenshot = await page.screenshot({ fullPage: true });
  await expectTestBridgeHidden(page);

  await writeFile(path.join(evidenceDir, "large-field-objective-ready.png"), readyScreenshot);
  await writeFile(path.join(evidenceDir, "large-field-objective-enroute.png"), enrouteScreenshot);
  await writeFile(path.join(evidenceDir, "large-field-objective-complete-or-progress.png"), progressScreenshot);
  await writeFile(
    path.join(evidenceDir, "browser-large-field-navigation-objective-v1.md"),
    createMarkdown([ready, enroute, progress]),
    "utf8"
  );
});
