import { expect, test, type Page } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const evidenceDir = path.resolve(process.cwd(), "evidence");

interface ObjectiveChainSnapshot {
  readonly phase: string;
  readonly objective: string;
  readonly status: string;
  readonly target: string;
  readonly distanceDisplay: string;
  readonly distanceMeters: number;
  readonly nextAction: string;
  readonly hint: string;
  readonly options: string;
  readonly selectedTarget: string;
  readonly routeStatus: string;
  readonly autopilotState: string;
}

const distanceFromHud = (text: string): number => {
  const match = text.match(/([\d.]+)\s*(km|m)\b/i);
  if (!match) {
    throw new Error(`Missing HUD distance in m or km: ${text}`);
  }

  const value = Number(match[1]);
  return match[2].toLowerCase() === "km" ? value * 1000 : value;
};

const textFrom = async (page: Page, selector: string): Promise<string> =>
  (await page.locator(selector).innerText()).trim();

async function expectTestBridgeAbsent(page: Page): Promise<void> {
  await expect.poll(() => page.evaluate(() => Object.prototype.hasOwnProperty.call(window, "TestBridge"))).toBe(false);
  await expect(page.getByTestId("basic-hud")).not.toContainText("TestBridge");
  await expect(page.locator("body")).not.toContainText("TestBridge");
  await expect(page.locator("#debug-hud")).toBeHidden();
}

async function waitForRuntimeFrames(page: Page, frameCount: number): Promise<void> {
  await page.evaluate(async (frames) => {
    for (let index = 0; index < frames; index += 1) {
      await new Promise<void>((resolve) => requestAnimationFrame(() => resolve()));
    }
  }, frameCount);
}

async function readObjectiveSnapshot(page: Page, phase: string): Promise<ObjectiveChainSnapshot> {
  const distanceDisplay = await page.getByTestId("objective-distance").innerText();
  return {
    phase,
    objective: await page.getByTestId("objective-label").innerText(),
    status: await page.getByTestId("objective-status").innerText(),
    target: await page.getByTestId("objective-target").innerText(),
    distanceDisplay,
    distanceMeters: distanceFromHud(distanceDisplay),
    nextAction: await page.getByTestId("objective-next-action").innerText(),
    hint: await page.getByTestId("objective-hint").innerText(),
    options: await page.getByTestId("objective-options").innerText(),
    selectedTarget: await page.getByTestId("selected-target").innerText(),
    routeStatus: await textFrom(page, "#route-status"),
    autopilotState: await page.getByTestId("autopilot-active").innerText()
  };
}

async function waitFor500mComplete(page: Page): Promise<ObjectiveChainSnapshot> {
  const deadline = Date.now() + 70_000;
  let latest = await readObjectiveSnapshot(page, "500m-complete");

  while (Date.now() < deadline) {
    await waitForRuntimeFrames(page, 60);
    await page.waitForTimeout(500);
    latest = await readObjectiveSnapshot(page, "500m-complete");
    if (latest.objective === "Reach Range 500m" && latest.status === "Complete") {
      return latest;
    }
  }

  throw new Error(`Range 500m objective did not complete in the live wait budget. Last state: ${JSON.stringify(latest)}`);
}

async function waitFor1000mProgress(
  page: Page,
  initialDistanceMeters: number
): Promise<ObjectiveChainSnapshot> {
  const deadline = Date.now() + 30_000;
  let latest = await readObjectiveSnapshot(page, "1000m-ready-or-enroute");

  while (Date.now() < deadline) {
    await waitForRuntimeFrames(page, 60);
    await page.waitForTimeout(500);
    latest = await readObjectiveSnapshot(page, "1000m-ready-or-enroute");
    if (latest.status === "Complete" || latest.distanceMeters <= initialDistanceMeters - 10) {
      return latest;
    }
  }

  expect(latest.status).toMatch(/Route ready|Enroute|Complete/);
  return latest;
}

function createMarkdown(rows: readonly ObjectiveChainSnapshot[]): string {
  const timelineRows = rows
    .map((row) => `| ${row.phase} | ${row.objective} | ${row.status} | ${row.target} | ${row.distanceDisplay} | ${row.distanceMeters} | ${row.nextAction} | ${row.selectedTarget} | ${row.autopilotState} |`)
    .join("\n");
  const selectedTargetRows = rows
    .map((row) => `| ${row.phase} | ${row.selectedTarget} | ${row.routeStatus} |`)
    .join("\n");
  const ready = rows.find((row) => row.phase === "ready");
  const oneThousand = rows.find((row) => row.phase === "1000m-ready-or-enroute");
  const oneThousandOutcome = oneThousand?.status === "Complete"
    ? "Range 1000m reached complete inside the live E2E budget."
    : "Range 1000m full arrival is deferred; this run proves route-ready/enroute state plus live distance reduction.";

  return `# Browser Large-Field Objective Chain Live v1 Evidence

Generated by \`apps/weltraum-browser/tests/e2e/large-field-objective-chain-live.spec.ts\`.

## Runtime Contract

- URL: normal browser runtime \`/\`
- TestBridge: absent from \`window\`, absent from the visible HUD, and no \`/?testBridge=1\` route was used
- Interaction path: player HUD buttons only
- Ship visual: Demo Scout GLB player-facing source line confirmed before objective flight

## Objective State Timeline

| Phase | Objective | Status | Target | HUD distance | Parsed distance (m) | Next action | Selected target | Autopilot state |
| --- | --- | --- | --- | --- | ---: | --- | --- | --- |
${timelineRows}

## Selected Target Timeline

| Phase | Selected target | Route status |
| --- | --- | --- |
${selectedTargetRows}

## Live Movement

- Initial 500m objective distance: ${ready?.distanceDisplay ?? "unknown"}
- Later 1000m objective distance: ${oneThousand?.distanceDisplay ?? "unknown"}
- 1000m outcome: ${oneThousandOutcome}

## Screenshots

- \`apps/weltraum-browser/evidence/objective-chain-ready.png\`
- \`apps/weltraum-browser/evidence/objective-chain-500m-enroute.png\`
- \`apps/weltraum-browser/evidence/objective-chain-500m-complete.png\`
- \`apps/weltraum-browser/evidence/objective-chain-1000m-ready-or-enroute.png\`

## Tests Run

- \`npm run test:e2e -- tests/e2e/large-field-objective-chain-live.spec.ts\`
`;
}

test("normal runtime chains large-field objectives from 500m completion into 1000m flight", async ({ page }) => {
  test.setTimeout(125_000);
  await mkdir(evidenceDir, { recursive: true });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.goto("/");
  await page.waitForSelector("#debug-scene", { state: "visible" });
  await expect(page.getByTestId("basic-hud")).toBeVisible();
  await expectTestBridgeAbsent(page);
  await expect(page.getByTestId("ship-visual-source")).toContainText("Ship visual: Demo Scout GLB", { timeout: 20_000 });

  await expect(page.getByTestId("objective-label")).toContainText("Reach Range 500m");
  await expect(page.getByTestId("objective-status")).toContainText("Available");
  await expect(page.getByTestId("objective-options")).toContainText("Reach Range 500m (available)");
  await expect(page.getByTestId("objective-options")).toContainText("Reach Range 1000m (locked)");
  await expect(page.getByTestId("objective-options")).toContainText("Reach Range 2500m (locked)");

  await page.locator('button[data-objective-id="reach-range-500m"]').click();
  await expect(page.getByTestId("selected-target")).toContainText("Range 500m");
  await expect(page.getByTestId("objective-status")).toContainText("Route ready");
  await expect(page.getByTestId("objective-next-action")).toContainText("engage autopilot");
  const ready = await readObjectiveSnapshot(page, "ready");
  const readyScreenshot = await page.screenshot({ fullPage: true });

  await page.locator("#engage-autopilot").click();
  await expect(page.getByTestId("autopilot-active")).toContainText(/Autopilot executing|Arrived at selected target/);
  await expect(page.getByTestId("objective-status")).toContainText(/Enroute|Complete/);
  const enroute = await readObjectiveSnapshot(page, "500m-enroute");
  const enrouteScreenshot = await page.screenshot({ fullPage: true });

  const complete500m = await waitFor500mComplete(page);
  expect(complete500m.nextAction).toBe("next objective available");
  expect(complete500m.hint).toContain("Reach Range 1000m is available");
  expect(complete500m.options).toContain("Reach Range 500m (complete)");
  expect(complete500m.options).toContain("Reach Range 1000m (available)");
  expect(complete500m.options).toContain("Reach Range 2500m (locked)");
  const completeScreenshot = await page.screenshot({ fullPage: true });

  await page.locator('button[data-objective-id="reach-range-1000m"]').click();
  await expect(page.getByTestId("objective-label")).toContainText("Reach Range 1000m");
  await expect(page.getByTestId("selected-target")).toContainText("Range 1000m");
  await expect(page.getByTestId("objective-status")).toContainText("Route ready");
  await expect(page.getByTestId("objective-options")).toContainText("Reach Range 500m (complete)");
  await expect(page.getByTestId("objective-options")).toContainText("Reach Range 1000m (route ready)");
  const ready1000m = await readObjectiveSnapshot(page, "1000m-ready");

  await page.locator("#engage-autopilot").click();
  await expect(page.getByTestId("objective-status")).toContainText(/Enroute|Complete/);
  const progress1000m = await waitFor1000mProgress(page, ready1000m.distanceMeters);
  expect(progress1000m.objective).toBe("Reach Range 1000m");
  expect(progress1000m.status).toMatch(/Enroute|Complete/);
  expect(progress1000m.distanceMeters).toBeLessThan(ready1000m.distanceMeters);
  const progressScreenshot = await page.screenshot({ fullPage: true });
  await expectTestBridgeAbsent(page);

  await writeFile(path.join(evidenceDir, "objective-chain-ready.png"), readyScreenshot);
  await writeFile(path.join(evidenceDir, "objective-chain-500m-enroute.png"), enrouteScreenshot);
  await writeFile(path.join(evidenceDir, "objective-chain-500m-complete.png"), completeScreenshot);
  await writeFile(path.join(evidenceDir, "objective-chain-1000m-ready-or-enroute.png"), progressScreenshot);
  await writeFile(
    path.join(evidenceDir, "browser-large-field-objective-chain-live-v1.md"),
    createMarkdown([ready, enroute, complete500m, ready1000m, progress1000m]),
    "utf8"
  );
});
