import { expect, test, type Page } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const evidenceDir = path.resolve(process.cwd(), "evidence");

interface ObjectiveEvidence {
  readonly phase: string;
  readonly label: string;
  readonly status: string;
  readonly target: string;
  readonly distanceDisplay: string;
  readonly distanceMeters: number;
  readonly nextAction: string;
  readonly hint: string;
}

const distanceFromHud = (text: string): number => {
  const match = text.match(/([\d.]+)\s*(km|m)\b/);
  if (!match) {
    throw new Error(`Missing HUD distance in m or km: ${text}`);
  }
  const value = Number(match[1]);
  return match[2] === "km" ? value * 1000 : value;
};

async function expectTestBridgeHidden(page: Page): Promise<void> {
  await expect.poll(() => page.evaluate(() => "TestBridge" in window)).toBe(false);
  await expect(page.getByTestId("basic-hud")).not.toContainText("TestBridge");
}

async function readObjectiveEvidence(page: Page, phase: string): Promise<ObjectiveEvidence> {
  const distanceDisplay = await page.getByTestId("objective-distance").innerText();
  return {
    phase,
    label: await page.getByTestId("objective-label").innerText(),
    status: await page.getByTestId("objective-status").innerText(),
    target: await page.getByTestId("objective-target").innerText(),
    distanceDisplay,
    distanceMeters: distanceFromHud(distanceDisplay),
    nextAction: await page.getByTestId("objective-next-action").innerText(),
    hint: await page.getByTestId("objective-hint").innerText()
  };
}

function createMarkdown(rows: readonly ObjectiveEvidence[]): string {
  const tableRows = rows
    .map((row) => `| ${row.phase} | ${row.label} | ${row.status} | ${row.target} | ${row.distanceDisplay} | ${row.distanceMeters} | ${row.nextAction} | ${row.hint} |`)
    .join("\n");

  return `# Browser Large-Field Navigation Objective v1 Evidence

Generated by \`apps/weltraum-browser/tests/e2e/large-field-navigation-objective.spec.ts\` against the normal product URL \`/\`.

## Objective Runtime Results

| Phase | Objective | Status | Target | HUD distance | Parsed distance (m) | Next action | Hint |
| --- | --- | --- | --- | --- | ---: | --- | --- |
${tableRows}

## Screenshots

- \`apps/weltraum-browser/evidence/large-field-objective-ready.png\`
- \`apps/weltraum-browser/evidence/large-field-objective-enroute.png\`
- \`apps/weltraum-browser/evidence/large-field-objective-complete-or-progress.png\`

## Guardrails

- Default \`/\` kept \`window.TestBridge\` absent.
- Demo Scout GLB loaded through the normal runtime.
- Objective target focus, route preview, and autopilot engage used player HUD buttons.
- Objective progress was observed from player HUD distance/status, not renderer-only markers or TestBridge helpers.
`;
}

test("normal runtime presents and progresses the Range 500m navigation objective", async ({ page }) => {
  await mkdir(evidenceDir, { recursive: true });
  await page.goto("/");
  await page.waitForSelector("#debug-scene", { state: "visible" });
  await expectTestBridgeHidden(page);
  await expect(page.getByTestId("ship-visual-source")).toContainText("Ship visual: Demo Scout GLB", { timeout: 20_000 });

  await expect(page.getByTestId("objective-label")).toContainText("Reach Range 500m");
  await expect(page.getByTestId("objective-status")).toContainText("Active");
  await expect(page.getByTestId("objective-target")).toContainText("Range 500m");
  await expect(page.getByTestId("objective-next-action")).toContainText("select target");
  await expect(page.getByTestId("objective-options")).toContainText("Reach Range 500m");

  await page.locator('button[data-objective-id="reach-range-500m"]').click();
  await expect(page.getByTestId("selected-target")).toContainText("Range 500m");
  await expect(page.locator("#route-status")).toContainText("preview ready");
  await expect(page.getByTestId("objective-status")).toContainText("Route ready");
  await expect(page.getByTestId("objective-next-action")).toContainText("engage autopilot");
  await expect(page.getByTestId("objective-hint")).toContainText("engage autopilot");
  const ready = await readObjectiveEvidence(page, "ready");
  await page.screenshot({ path: path.join(evidenceDir, "large-field-objective-ready.png"), fullPage: true });

  await page.locator("#engage-autopilot").click();
  await expect(page.getByTestId("autopilot-active")).toContainText("Autopilot executing");
  await expect(page.getByTestId("objective-status")).toContainText(/Enroute|Complete/);
  const enroute = await readObjectiveEvidence(page, "enroute");
  await page.screenshot({ path: path.join(evidenceDir, "large-field-objective-enroute.png"), fullPage: true });

  await expect.poll(async () => {
    const evidence = await readObjectiveEvidence(page, "progress");
    return evidence.distanceMeters;
  }, { timeout: 12_000 }).toBeLessThan(ready.distanceMeters - 2);

  const progress = await readObjectiveEvidence(page, "complete-or-progress");
  expect(progress.distanceMeters).toBeLessThan(ready.distanceMeters);
  expect(progress.status).toMatch(/Enroute|Complete/);
  await page.screenshot({ path: path.join(evidenceDir, "large-field-objective-complete-or-progress.png"), fullPage: true });
  await expectTestBridgeHidden(page);

  await writeFile(
    path.join(evidenceDir, "browser-large-field-navigation-objective-v1.md"),
    createMarkdown([ready, enroute, progress]),
    "utf8"
  );
});
