import { expect, test, type Page } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { engageVisiblePreview, selectVisiblePlannerTarget } from "./support/plannerWorkflow";

const evidenceDir = path.resolve(process.cwd(), "evidence");

interface TargetPreviewEvidence {
  readonly targetId: string;
  readonly label: string;
  readonly hudDistanceDisplay: string;
  readonly hudDistanceMeters: number;
  readonly routeStatus: string;
  readonly radarStatus: string;
  readonly previewPlanHash: string;
}

const largeTargets = [
  { targetId: "range-500m", label: "Range 500m", minMeters: 500, maxMeters: 820 },
  { targetId: "range-1000m", label: "Range 1000m", minMeters: 1_000, maxMeters: 1_420 },
  { targetId: "range-2500m", label: "Range 2500m", minMeters: 2_500, maxMeters: 3_200 }
] as const;

const distanceFromHud = (text: string): number => {
  const match = text.match(/([\d.]+)\s*(km|m)\b/);
  if (!match) {
    throw new Error(`Missing HUD distance in m or km: ${text}`);
  }
  const value = Number(match[1]);
  return match[2] === "km" ? value * 1000 : value;
};

async function expectTestBridgeHidden(page: Page): Promise<void> {
  await expect.poll(() => page.evaluate(() => "TestBridge" in window)).toBe(false);
  await expect(page.getByTestId("basic-hud")).not.toContainText("TestBridge");
}

async function selectTargetAndAssertPreview(page: Page, target: (typeof largeTargets)[number]): Promise<TargetPreviewEvidence> {
  const previewPlanHash = await selectVisiblePlannerTarget(page, target.targetId, target.label);
  await page.locator("#planner-close").click();
  await expect(page.getByTestId("selected-target")).toContainText(target.label);
  await expect(page.locator("#route-status")).toContainText(/preview ready/i);
  await expect(page.locator("#route-status")).toHaveAttribute("title", /preview ready: \d+ legs?, route/i);
  await expect(page.getByTestId("radar-status")).toContainText(/^\d+ contacts$/i);
  await expect(page.getByTestId("radar-status")).toHaveAttribute("title", new RegExp(target.label, "i"));

  const distanceText = await page.locator("#target-distance").innerText();
  const routeStatus = (await page.locator("#route-status").getAttribute("title")) ?? "";
  const radarStatus = (await page.getByTestId("radar-status").getAttribute("title")) ?? "";
  const hudDistanceMeters = distanceFromHud(distanceText);

  expect(hudDistanceMeters).toBeGreaterThanOrEqual(target.minMeters);
  expect(hudDistanceMeters).toBeLessThan(target.maxMeters);

  return {
    targetId: target.targetId,
    label: target.label,
    hudDistanceDisplay: distanceText,
    hudDistanceMeters,
    routeStatus,
    radarStatus,
    previewPlanHash
  };
}

function createMarkdown(results: readonly TargetPreviewEvidence[]): string {
  const rows = results
    .map((result) => `| ${result.targetId} | ${result.label} | ${result.hudDistanceDisplay} | ${result.hudDistanceMeters} | ${result.previewPlanHash} | ${result.routeStatus} | ${result.radarStatus} |`)
    .join("\n");

  return `# Browser Playable Large Proving Ground v1 Evidence

Generated by \`apps/weltraum-browser/tests/e2e/playable-large-proving-ground.spec.ts\` from the normal browser runtime at \`/\`.

## Preview Results

| Target ID | Label | HUD distance display | Parsed distance (m) | Preview hash | Route status | Radar status |
| --- | --- | --- | ---: | --- | --- | --- |
${rows}

## Screenshots

- \`apps/weltraum-browser/evidence/playable-large-field-overview.png\`
- \`apps/weltraum-browser/evidence/playable-large-field-1000m-target.png\`
- \`apps/weltraum-browser/evidence/playable-large-field-2500m-target.png\`

## Guardrails

- TestBridge stayed hidden on the default URL.
- Demo Scout GLB loaded through the normal runtime.
- Target selection and Engage used the visible navigation planner, not TestBridge helpers.
- Runtime obstacles are provided by \`browserObstacles\`; range asteroids and gate markers are render-only landmarks.
`;
}

test("normal browser runtime exposes and previews the playable large proving-ground targets", async ({ page }) => {
  await mkdir(evidenceDir, { recursive: true });
  await page.goto("/");
  await page.waitForSelector("#debug-scene", { state: "visible" });
  await expectTestBridgeHidden(page);
  await expect(page.getByTestId("ship-visual-source")).toContainText("Ship visual: Demo Scout GLB", { timeout: 20_000 });

  await page.screenshot({ path: path.join(evidenceDir, "playable-large-field-overview.png"), fullPage: true });

  const range500 = await selectTargetAndAssertPreview(page, largeTargets[0]);
  const range1000 = await selectTargetAndAssertPreview(page, largeTargets[1]);
  expect(range1000.hudDistanceDisplay).toContain("km");
  expect(range1000.routeStatus).toContain("route 1.");
  expect(range1000.radarStatus).toContain("auto range 1.0 km");
  await page.screenshot({ path: path.join(evidenceDir, "playable-large-field-1000m-target.png"), fullPage: true });
  const range2500 = await selectTargetAndAssertPreview(page, largeTargets[2]);
  expect(range2500.hudDistanceDisplay).toContain("km");
  expect(range2500.routeStatus).toContain("route 2.");
  expect(range2500.radarStatus).toContain("auto range 2.5 km");
  await page.screenshot({ path: path.join(evidenceDir, "playable-large-field-2500m-target.png"), fullPage: true });

  const selectedForFlight = await selectTargetAndAssertPreview(page, largeTargets[0]);
  await engageVisiblePreview(page, selectedForFlight.previewPlanHash);
  await expect(page.getByTestId("autopilot-active")).toContainText("Autopilot executing");
  await expect(page.locator("#autopilot-action-state")).toContainText(/Cancel current route|Ready|Holding|Cancel/);
  await expectTestBridgeHidden(page);

  await writeFile(path.join(evidenceDir, "browser-playable-large-proving-ground-v1.md"), createMarkdown([range500, range1000, range2500]), "utf8");
});
