import { expect, test, type Page } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const evidenceDir = path.resolve(process.cwd(), "evidence");
const summaryPath = path.join(evidenceDir, "browser-resource-cargo-inventory-core-v1-summary.json");
const markdownPath = path.join(evidenceDir, "browser-resource-cargo-inventory-core-v1.md");
const generator = "apps/weltraum-browser/tests/e2e/resource-cargo-core.spec.ts";
const focusedCommand = "npm run test:e2e -- tests/e2e/resource-cargo-core.spec.ts";

interface NormalPageGuard {
  readonly route: string;
  readonly testBridgeOwnProperty: boolean;
  readonly testBridgeInWindow: boolean;
  readonly bodyContainsTestBridge: boolean;
  readonly debugHudVisible: boolean;
}

interface TransferScenarioEvidence {
  readonly id: string;
  readonly status: string;
  readonly code: string | null;
  readonly requestedQuantity: number;
  readonly acceptedQuantity: number;
  readonly rejectedQuantity: number;
  readonly issues: readonly string[];
  readonly warnings: readonly string[];
  readonly sourceRevisions: { readonly before: number; readonly after: number };
  readonly targetRevisions: { readonly before: number; readonly after: number };
  readonly sourceSignatures: { readonly before: string; readonly after: string };
  readonly targetSignatures: { readonly before: string; readonly after: string };
  readonly sourceStacks: readonly Record<string, unknown>[];
  readonly targetStacks: readonly Record<string, unknown>[];
  readonly metadataPreserved: boolean;
  readonly rejectedSnapshotUnchanged: boolean | null;
}

interface ResourceCargoSmokeRun {
  readonly modulePath: string;
  readonly importedPublicApi: readonly string[];
  readonly catalogSignature: string;
  readonly validationOrder: readonly string[];
  readonly scenarios: readonly TransferScenarioEvidence[];
  readonly suiteSignature: string;
  readonly canonicalResult: string;
}

interface ResourceCargoSmokeEvidence {
  readonly schemaVersion: "browser-resource-cargo-inventory-core-v1";
  readonly generator: string;
  readonly test: string;
  readonly normalPageGuard: NormalPageGuard;
  readonly dynamicImport: {
    readonly modulePath: string;
    readonly importedPublicApi: readonly string[];
  };
  readonly deterministicRepeat: {
    readonly identicalCanonicalResult: boolean;
    readonly identicalSuiteSignature: boolean;
    readonly suiteSignature: string;
    readonly catalogSignature: string;
  };
  readonly scenarios: readonly TransferScenarioEvidence[];
  readonly stableTransferStatuses: readonly string[];
  readonly stableRejectionCodes: readonly string[];
  readonly scope: readonly string[];
  readonly nonGoals: readonly string[];
  readonly verification: {
    readonly command: string;
    readonly expectedResult: string;
    readonly observedResult: string;
    readonly screenshot: "not captured: no visual change";
  };
}

async function expectNormalPageTestBridgeGuard(page: Page): Promise<NormalPageGuard> {
  await page.goto("/");
  await page.waitForSelector("#debug-scene", { state: "visible" });

  await expect.poll(() => page.evaluate(() => Object.prototype.hasOwnProperty.call(window, "TestBridge"))).toBe(false);
  await expect.poll(() => page.evaluate(() => "TestBridge" in window)).toBe(false);
  await expect(page.getByTestId("basic-hud")).not.toContainText("TestBridge");
  await expect(page.locator("body")).not.toContainText("TestBridge");
  await expect(page.locator("#debug-hud")).toBeHidden();

  const guard = await page.evaluate(() => ({
    route: location.pathname,
    testBridgeOwnProperty: Object.prototype.hasOwnProperty.call(window, "TestBridge"),
    testBridgeInWindow: "TestBridge" in window,
    bodyContainsTestBridge: (document.body.textContent ?? "").includes("TestBridge"),
    debugHudVisible: document.querySelector<HTMLElement>("#debug-hud")?.offsetParent !== null
  }));

  expect(guard).toEqual({
    route: "/",
    testBridgeOwnProperty: false,
    testBridgeInWindow: false,
    bodyContainsTestBridge: false,
    debugHudVisible: false
  });

  return guard;
}

function createMarkdown(evidence: ResourceCargoSmokeEvidence): string {
  const scenarioRows = evidence.scenarios
    .map(
      (scenario) =>
        `| ${scenario.id} | ${scenario.status} | ${scenario.code ?? "—"} | ${scenario.requestedQuantity} | ${scenario.acceptedQuantity} | ${scenario.rejectedQuantity} | ${scenario.sourceRevisions.before} → ${scenario.sourceRevisions.after} | ${scenario.targetRevisions.before} → ${scenario.targetRevisions.after} | ${scenario.sourceSignatures.after} | ${scenario.targetSignatures.after} |`
    )
    .join("\n");

  return `# Browser Resource Cargo Inventory Core v1 Evidence

Generated by \`${evidence.generator}\`.

## Normal Page Guard

- Route: \`${evidence.normalPageGuard.route}\`
- TestBridge own property: \`${evidence.normalPageGuard.testBridgeOwnProperty}\`
- TestBridge present in window: \`${evidence.normalPageGuard.testBridgeInWindow}\`
- Body contains TestBridge: \`${evidence.normalPageGuard.bodyContainsTestBridge}\`
- Debug HUD visible: \`${evidence.normalPageGuard.debugHudVisible}\`

## Public Module Import

- Dynamic import: \`${evidence.dynamicImport.modulePath}\`
- Imported API used: ${evidence.dynamicImport.importedPublicApi.map((name) => `\`${name}\``).join(", ")}
- Repeated canonical result is identical: \`${evidence.deterministicRepeat.identicalCanonicalResult}\`
- Repeated suite signature is identical: \`${evidence.deterministicRepeat.identicalSuiteSignature}\`
- Catalog signature: \`${evidence.deterministicRepeat.catalogSignature}\`
- Suite signature: \`${evidence.deterministicRepeat.suiteSignature}\`

## Transfer Scenarios

| Scenario | Status | Code | Requested | Accepted | Rejected | Source revision | Target revision | Source signature after | Target signature after |
| --- | --- | --- | ---: | ---: | ---: | --- | --- | --- | --- |
${scenarioRows}

The full transfer preserves grade, condition, owner, legal status, and namespaced extension metadata. Capacity-limited partial transfer keeps the source stack ID and metadata. Mission-locked and sealed-split rejections retain their input snapshots, signatures, and revisions.

## Stable Contracts

- Statuses: ${evidence.stableTransferStatuses.map((status) => `\`${status}\``).join(", ")}
- Rejection codes: ${evidence.stableRejectionCodes.map((code) => `\`${code}\``).join(", ")}

## Scope And Non-Goals

${evidence.scope.map((item) => `- ${item}`).join("\n")}

### Deferred

${evidence.nonGoals.map((item) => `- ${item}`).join("\n")}

## Focused Verification

- Command: \`${evidence.verification.command}\`
- Expected result: ${evidence.verification.expectedResult}
- Observed result: ${evidence.verification.observedResult}
- Screenshot: ${evidence.verification.screenshot}
`;
}

test("normal page dynamically imports the resource cargo core and records deterministic evidence", async ({ page }) => {
  const normalPageGuard = await expectNormalPageTestBridgeGuard(page);

  const repeated = await page.evaluate(async (): Promise<{ readonly first: ResourceCargoSmokeRun; readonly second: ResourceCargoSmokeRun }> => {
    const resourceModulePath = "/src/resources/index.ts";
    const resources = await import(resourceModulePath);

    const runScenarioSuite = (): ResourceCargoSmokeRun => {
      const catalog = resources.createStarterResourceCatalog();
      const createDefinition = (
        containerId: string,
        kind: string,
        maxMassKg: number,
        maxVolumeM3: number,
        maxStackCount: number,
        policy: Record<string, unknown> = {}
      ) =>
        resources.createResourceContainerDefinition({
          containerId,
          kind,
          maxMassKg,
          maxVolumeM3,
          maxStackCount,
          policy
        });
      const createSnapshot = (definition: ReturnType<typeof resources.createResourceContainerDefinition>, state: Record<string, unknown>) =>
        resources.createResourceContainerSnapshot(
          definition,
          resources.createResourceContainerState(state, catalog),
          catalog
        );
      const stackSummary = (stacks: readonly Record<string, unknown>[]) =>
        stacks.map((stack) => ({
          stackId: stack.stackId,
          resourceId: stack.resourceId,
          quantity: stack.quantity,
          ...(stack.grade === undefined ? {} : { grade: stack.grade }),
          ...(stack.condition === undefined ? {} : { condition: stack.condition }),
          ...(stack.ownerId === undefined ? {} : { ownerId: stack.ownerId }),
          ...(stack.legalStatus === undefined ? {} : { legalStatus: stack.legalStatus }),
          ...(stack.missionId === undefined ? {} : { missionId: stack.missionId }),
          sealed: stack.sealed,
          extensions: stack.extensions
        }));
      const summarize = (
        id: string,
        result: ReturnType<typeof resources.transferResource>,
        sourceBefore: ReturnType<typeof resources.createResourceContainerSnapshot>,
        targetBefore: ReturnType<typeof resources.createResourceContainerSnapshot>,
        metadataPreserved: boolean
      ): TransferScenarioEvidence => {
        const rejectedSnapshotUnchanged =
          result.status === "Rejected"
            ? result.source === sourceBefore &&
              result.target === targetBefore &&
              result.sourceState === sourceBefore.state &&
              result.targetState === targetBefore.state &&
              result.sourceSignatureAfter === sourceBefore.state.signature &&
              result.targetSignatureAfter === targetBefore.state.signature &&
              result.sourceRevisionAfter === sourceBefore.state.revision &&
              result.targetRevisionAfter === targetBefore.state.revision &&
              resources.canonicalJson(result.sourceState.contents) === resources.canonicalJson(sourceBefore.state.contents) &&
              resources.canonicalJson(result.targetState.contents) === resources.canonicalJson(targetBefore.state.contents)
            : null;

        return {
          id,
          status: result.status,
          code: result.code ?? null,
          requestedQuantity: result.requestedQuantity,
          acceptedQuantity: result.acceptedQuantity,
          rejectedQuantity: result.rejectedQuantity,
          issues: [...result.issues],
          warnings: [...result.warnings],
          sourceRevisions: { before: result.sourceRevisionBefore, after: result.sourceRevisionAfter },
          targetRevisions: { before: result.targetRevisionBefore, after: result.targetRevisionAfter },
          sourceSignatures: { before: result.sourceSignatureBefore, after: result.sourceSignatureAfter },
          targetSignatures: { before: result.targetSignatureBefore, after: result.targetSignatureAfter },
          sourceStacks: stackSummary(result.sourceState.contents),
          targetStacks: stackSummary(result.targetState.contents),
          metadataPreserved,
          rejectedSnapshotUnchanged
        };
      };

      const fullSource = createSnapshot(
        createDefinition("suit_pack", "Suit", 30, 0.08, 4),
        {
          containerId: "suit_pack",
          contents: [
            {
              stackId: "suit_ore",
              resourceId: "ore_iron_silicate",
              quantity: 2,
              grade: "high",
              condition: 0.75,
              ownerId: "pilot",
              legalStatus: "Restricted",
              extensions: { "weltraum.e2e": { lot: "full_alpha" } }
            }
          ]
        }
      );
      const fullTarget = createSnapshot(
        createDefinition("ship_hold", "ShipCargo", 100, 1, 10),
        { containerId: "ship_hold", contents: [] }
      );
      const fullResult = resources.transferResource(
        {
          source: { containerId: "suit_pack", expectedRevision: 0 },
          target: { containerId: "ship_hold", expectedRevision: 0 },
          resourceId: "ore_iron_silicate",
          quantity: 2,
          targetStackId: "ship_ore",
          allowPartial: false,
          context: { actorId: "pilot" }
        },
        catalog,
        fullSource,
        fullTarget
      );
      const fullStack = fullResult.targetState.contents[0];
      const fullMetadataPreserved =
        fullStack?.stackId === "ship_ore" &&
        fullStack.grade === "high" &&
        fullStack.condition === 0.75 &&
        fullStack.ownerId === "pilot" &&
        fullStack.legalStatus === "Restricted" &&
        resources.canonicalJson(fullStack.extensions) === resources.canonicalJson({ "weltraum.e2e": { lot: "full_alpha" } });

      const partialSource = createSnapshot(
        createDefinition("partial_source", "ShipCargo", 100, 1, 10, { partialTransferPolicy: "Allowed" }),
        {
          containerId: "partial_source",
          contents: [
            {
              stackId: "partial_source_ore",
              resourceId: "ore_iron_silicate",
              quantity: 10,
              grade: "high",
              ownerId: "pilot",
              extensions: { "weltraum.e2e": { lot: "partial_alpha" } }
            }
          ]
        }
      );
      const partialTarget = createSnapshot(
        createDefinition("partial_target", "ShipCargo", 20, 1, 10, { partialTransferPolicy: "Allowed" }),
        { containerId: "partial_target", contents: [] }
      );
      const partialResult = resources.transferResource(
        {
          source: { containerId: "partial_source", expectedRevision: 0 },
          target: { containerId: "partial_target", expectedRevision: 0 },
          resourceId: "ore_iron_silicate",
          quantity: 3,
          targetStackId: "partial_target_ore",
          allowPartial: true,
          context: { actorId: "pilot" }
        },
        catalog,
        partialSource,
        partialTarget
      );
      const partialSourceStack = partialResult.sourceState.contents[0];
      const partialTargetStack = partialResult.targetState.contents[0];
      const partialMetadataPreserved =
        partialSourceStack?.stackId === "partial_source_ore" &&
        partialSourceStack.quantity === 7.5 &&
        partialTargetStack?.stackId === "partial_target_ore" &&
        partialTargetStack.quantity === 2.5 &&
        resources.canonicalJson(partialSourceStack.extensions) === resources.canonicalJson({ "weltraum.e2e": { lot: "partial_alpha" } }) &&
        resources.canonicalJson(partialTargetStack.extensions) === resources.canonicalJson({ "weltraum.e2e": { lot: "partial_alpha" } });

      const missionSource = createSnapshot(
        createDefinition("mission_source", "ShipCargo", 100, 1, 10),
        {
          containerId: "mission_source",
          missionId: "mission_alpha",
          contents: [{ stackId: "mission_ore", resourceId: "ore_iron_silicate", quantity: 1 }]
        }
      );
      const missionTarget = createSnapshot(
        createDefinition("mission_target", "ShipCargo", 100, 1, 10),
        { containerId: "mission_target", contents: [] }
      );
      const missionResult = resources.transferResource(
        {
          source: { containerId: "mission_source", expectedRevision: 0 },
          target: { containerId: "mission_target", expectedRevision: 0 },
          resourceId: "ore_iron_silicate",
          quantity: 1,
          allowPartial: false,
          context: { actorId: "pilot" }
        },
        catalog,
        missionSource,
        missionTarget
      );

      const sealedSource = createSnapshot(
        createDefinition("sealed_source", "ShipCargo", 200, 1, 10, { partialTransferPolicy: "Allowed" }),
        {
          containerId: "sealed_source",
          contents: [
            { stackId: "sealed_ore", resourceId: "ore_iron_silicate", quantity: 2, sealed: true }
          ]
        }
      );
      const sealedTarget = createSnapshot(
        createDefinition("sealed_target", "ShipCargo", 100, 1, 10, { partialTransferPolicy: "Allowed" }),
        { containerId: "sealed_target", contents: [] }
      );
      const sealedResult = resources.transferResource(
        {
          source: { containerId: "sealed_source", expectedRevision: 0 },
          target: { containerId: "sealed_target", expectedRevision: 0 },
          resourceId: "ore_iron_silicate",
          quantity: 1,
          sourceStackId: "sealed_ore",
          allowPartial: true,
          context: { actorId: "pilot" }
        },
        catalog,
        sealedSource,
        sealedTarget
      );

      const scenarios = [
        summarize("full-suit-to-ship", fullResult, fullSource, fullTarget, fullMetadataPreserved),
        summarize("capacity-limited-explicit-partial", partialResult, partialSource, partialTarget, partialMetadataPreserved),
        summarize("mission-locked-rejection", missionResult, missionSource, missionTarget, true),
        summarize("sealed-split-rejection", sealedResult, sealedSource, sealedTarget, true)
      ];
      const payload = {
        modulePath: "/src/resources/index.ts",
        importedPublicApi: [
          "createStarterResourceCatalog",
          "createResourceContainerDefinition",
          "createResourceContainerState",
          "createResourceContainerSnapshot",
          "transferResource",
          "canonicalJson",
          "canonicalSignature"
        ],
        catalogSignature: catalog.signature,
        validationOrder: [...resources.RESOURCE_TRANSFER_VALIDATION_ORDER],
        scenarios
      };
      const canonicalResult = resources.canonicalJson(payload);

      return {
        ...payload,
        suiteSignature: resources.canonicalSignature(payload),
        canonicalResult
      };
    };

    return { first: runScenarioSuite(), second: runScenarioSuite() };
  });

  expect(repeated.first.canonicalResult).toBe(repeated.second.canonicalResult);
  expect(repeated.first.suiteSignature).toBe(repeated.second.suiteSignature);
  expect(repeated.first.catalogSignature).toBe(repeated.second.catalogSignature);
  expect(repeated.first.importedPublicApi).toEqual([
    "createStarterResourceCatalog",
    "createResourceContainerDefinition",
    "createResourceContainerState",
    "createResourceContainerSnapshot",
    "transferResource",
    "canonicalJson",
    "canonicalSignature"
  ]);

  const [full, partial, missionLocked, sealedSplit] = repeated.first.scenarios;
  expect(full).toMatchObject({
    id: "full-suit-to-ship",
    status: "Accepted",
    code: null,
    requestedQuantity: 2,
    acceptedQuantity: 2,
    rejectedQuantity: 0,
    sourceRevisions: { before: 0, after: 1 },
    targetRevisions: { before: 0, after: 1 },
    metadataPreserved: true,
    rejectedSnapshotUnchanged: null
  });
  expect(full.sourceStacks).toEqual([]);
  expect(full.targetStacks).toEqual([
    expect.objectContaining({
      stackId: "ship_ore",
      resourceId: "ore_iron_silicate",
      quantity: 2,
      grade: "high",
      condition: 0.75,
      ownerId: "pilot",
      legalStatus: "Restricted",
      extensions: { "weltraum.e2e": { lot: "full_alpha" } }
    })
  ]);

  expect(partial).toMatchObject({
    id: "capacity-limited-explicit-partial",
    status: "PartiallyAccepted",
    code: null,
    requestedQuantity: 3,
    acceptedQuantity: 2.5,
    rejectedQuantity: 0.5,
    issues: ["TargetMassExceeded"],
    sourceRevisions: { before: 0, after: 1 },
    targetRevisions: { before: 0, after: 1 },
    metadataPreserved: true,
    rejectedSnapshotUnchanged: null
  });
  expect(partial.sourceStacks).toEqual([expect.objectContaining({ stackId: "partial_source_ore", quantity: 7.5 })]);
  expect(partial.targetStacks).toEqual([expect.objectContaining({ stackId: "partial_target_ore", quantity: 2.5 })]);

  expect(missionLocked).toMatchObject({
    id: "mission-locked-rejection",
    status: "Rejected",
    code: "MissionLocked",
    requestedQuantity: 1,
    acceptedQuantity: 0,
    rejectedQuantity: 1,
    issues: ["MissionLocked"],
    sourceRevisions: { before: 0, after: 0 },
    targetRevisions: { before: 0, after: 0 },
    metadataPreserved: true,
    rejectedSnapshotUnchanged: true
  });

  expect(sealedSplit).toMatchObject({
    id: "sealed-split-rejection",
    status: "Rejected",
    code: "SealedStackCannotSplit",
    requestedQuantity: 1,
    acceptedQuantity: 0,
    rejectedQuantity: 1,
    issues: ["SealedStackCannotSplit"],
    sourceRevisions: { before: 0, after: 0 },
    targetRevisions: { before: 0, after: 0 },
    metadataPreserved: true,
    rejectedSnapshotUnchanged: true
  });

  const evidence: ResourceCargoSmokeEvidence = {
    schemaVersion: "browser-resource-cargo-inventory-core-v1",
    generator,
    test: "normal page dynamically imports the resource cargo core and records deterministic evidence",
    normalPageGuard,
    dynamicImport: {
      modulePath: repeated.first.modulePath,
      importedPublicApi: repeated.first.importedPublicApi
    },
    deterministicRepeat: {
      identicalCanonicalResult: repeated.first.canonicalResult === repeated.second.canonicalResult,
      identicalSuiteSignature: repeated.first.suiteSignature === repeated.second.suiteSignature,
      suiteSignature: repeated.first.suiteSignature,
      catalogSignature: repeated.first.catalogSignature
    },
    scenarios: repeated.first.scenarios,
    stableTransferStatuses: ["Accepted", "PartiallyAccepted", "Rejected"],
    stableRejectionCodes: repeated.first.validationOrder,
    scope: [
      "Normal / startup with TestBridge absent from window, body, and debug HUD.",
      "In-page dynamic import of the public /src/resources/index.ts module.",
      "Deterministic full, capacity-limited partial, mission-locked, and sealed-split transfer results."
    ],
    nonGoals: [
      "No runtime, UI, renderer, simulator, flight, or Ship Builder integration.",
      "No economy consequences, mining gameplay loop, screenshot, clock, random value, duration, or machine-specific path."
    ],
    verification: {
      command: focusedCommand,
      expectedResult: "one focused Playwright test passes and writes these two task-owned evidence files",
      observedResult: "pass",
      screenshot: "not captured: no visual change"
    }
  };

  await mkdir(evidenceDir, { recursive: true });
  await writeFile(summaryPath, `${JSON.stringify(evidence, null, 2)}\n`, "utf8");
  await writeFile(markdownPath, createMarkdown(evidence), "utf8");
});
