import { expect, test } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type {
  ShipBlueprintStructureReport,
  ShipBuilderMassPropertiesReport,
  ShipBuilderValidationPolicy
} from "../../src/ship-builder";

type ShipBuilderDomain = typeof import("../../src/ship-builder/index");

const evidenceDir = path.resolve(process.cwd(), "evidence");
const summaryPath = path.join(evidenceDir, "browser-ship-builder-compatibility-mass-core-v1-summary.json");
const markdownPath = path.join(evidenceDir, "browser-ship-builder-compatibility-mass-core-v1.md");

type FixtureName = "scout" | "cargo" | "weapon";

interface BrowserFixtureReport {
  readonly fixture: FixtureName;
  readonly blueprintId: string;
  readonly layoutHash: string;
  readonly structure: ShipBlueprintStructureReport;
  readonly mass: ShipBuilderMassPropertiesReport;
}

interface BrowserShipBuilderCompatibilityMassSummary {
  readonly route: "/";
  readonly sourceModule: "/src/ship-builder/index.ts";
  readonly testBridgeAbsent: boolean;
  readonly catalogSignature: string;
  readonly policy: ShipBuilderValidationPolicy;
  readonly policyJsonRoundTripEqual: boolean;
  readonly reportsDeeplyFrozen: boolean;
  readonly reportsJsonSafe: boolean;
  readonly fixtures: readonly BrowserFixtureReport[];
  readonly uiIntegration: "none";
  readonly screenshotStatus: "not-captured-no-visual-contract";
  readonly nonGoals: readonly string[];
}

const createMarkdown = (summary: BrowserShipBuilderCompatibilityMassSummary): string => {
  const tick = String.fromCharCode(96);
  const rows = summary.fixtures
    .map(
      (fixture) =>
        "| " +
        fixture.fixture +
        " | " +
        tick +
        (fixture.structure.rootComponent?.rootInstanceId ?? "none") +
        tick +
        " | " +
        (fixture.mass.dryMassKg ?? "null") +
        " | " +
        fixture.structure.summary.occupiedSocketEndpointCount +
        " | " +
        tick +
        fixture.structure.signature +
        tick +
        " | " +
        tick +
        fixture.mass.signature +
        tick +
        " |"
    )
    .join("\n");

  return [
    "# Browser Ship Builder Compatibility & Mass Core v1 Evidence",
    "",
    "Generated by " +
      tick +
      "apps/weltraum-browser/tests/e2e/ship-builder-compatibility-mass-core.spec.ts" +
      tick +
      " through a normal-route Vite module import.",
    "",
    "## Fixture Summary",
    "",
    "| Fixture | Root | Dry mass (kg) | Occupied endpoints | Structure signature | Mass signature |",
    "| --- | --- | ---: | ---: | --- | --- |",
    rows,
    "",
    "## Deterministic Report Payload",
    "",
    tick.repeat(3) + "json",
    JSON.stringify(summary, null, 2),
    tick.repeat(3),
    "",
    "## Guardrail Confirmation",
    "",
    "- The browser loaded normal " + tick + "/" + tick + "; " + tick + "window.TestBridge" + tick + " remained absent.",
    "- The browser dynamically imported " +
      tick +
      "/src/ship-builder/index.ts" +
      tick +
      " through Vite without adding a route, runtime hook, UI integration, renderer dependency, or query gate.",
    "- Catalog signature " +
      tick +
      summary.catalogSignature +
      tick +
      " and policy signature " +
      tick +
      summary.policy.signature +
      tick +
      " are pinned by the test.",
    "- All fixture structure and mass reports are JSON-safe, deeply frozen, deterministically signed, and included above without timestamps.",
    "- Scout, Cargo, and Weapon each have one root-connected component, no disconnected instances, no unused required sockets, and the planned occupied-endpoint counts.",
    "- Dry mass uses enabled part-definition dry mass only. COM and bounds are ship-local analysis output, not flight/runtime authority.",
    "- No screenshot was captured because this task has no visual contract or UI change.",
    ""
  ].join("\n");
};

test("normal browser route evaluates ship-builder compatibility and mass reports with deterministic evidence", async ({ page }) => {
  await page.goto("/");
  await expect.poll(() => page.evaluate(() => "TestBridge" in window)).toBe(false);

  const summary = await page.evaluate<BrowserShipBuilderCompatibilityMassSummary>(async () => {
    const sourceModule = String("/src/ship-builder/index.ts") as "/src/ship-builder/index.ts";
    const domain = (await import(/* @vite-ignore */ sourceModule)) as ShipBuilderDomain;
    const catalog = domain.createStarterCatalog();
    const policy = domain.STARTER_SHIP_BUILDER_VALIDATION_POLICY;
    const fixtureInputs = [
      ["scout", domain.SCOUT_BLUEPRINT],
      ["cargo", domain.CARGO_BLUEPRINT],
      ["weapon", domain.WEAPON_BLUEPRINT]
    ] as const;
    const fixtures = fixtureInputs.map(([fixture, blueprint]) => ({
      fixture,
      blueprintId: blueprint.blueprintId,
      layoutHash: domain.shipBlueprintLayoutHash(blueprint),
      structure: domain.validateShipBlueprintStructure(blueprint, catalog, policy),
      mass: domain.evaluateShipBlueprintMassProperties(blueprint, catalog)
    }));
    const policyJson = JSON.stringify(policy);
    const reportsDeeplyFrozen = fixtures.every(
      (fixture) =>
        Object.isFrozen(fixture.structure) &&
        Object.isFrozen(fixture.structure.diagnostics) &&
        Object.isFrozen(fixture.structure.connectedComponents) &&
        Object.isFrozen(fixture.structure.occupiedSocketEndpoints) &&
        Object.isFrozen(fixture.mass) &&
        Object.isFrozen(fixture.mass.contributions) &&
        Object.isFrozen(fixture.mass.diagnostics) &&
        Object.isFrozen(fixture.mass.summary)
    );
    const reportsJson = JSON.stringify(fixtures);

    return {
      route: "/",
      sourceModule,
      testBridgeAbsent: !("TestBridge" in window),
      catalogSignature: catalog.signature,
      policy,
      policyJsonRoundTripEqual: JSON.stringify(JSON.parse(policyJson)) === policyJson,
      reportsDeeplyFrozen,
      reportsJsonSafe: !/Infinity|NaN/.test(reportsJson) && JSON.stringify(JSON.parse(reportsJson)) === reportsJson,
      fixtures,
      uiIntegration: "none",
      screenshotStatus: "not-captured-no-visual-contract",
      nonGoals: [
        "Builder UI and placement workflow",
        "flight runtime and test-flight handoff",
        "thrust, authority, fuel, cargo, ammo, crew, and resource mass",
        "mesh, collider, overlap, proximity, and art-alias validation",
        "economy, recipes, unlocks, and final balance"
      ]
    };
  });

  expect(summary).toMatchObject({
    route: "/",
    sourceModule: "/src/ship-builder/index.ts",
    testBridgeAbsent: true,
    catalogSignature: "5aaa27fd",
    policyJsonRoundTripEqual: true,
    reportsDeeplyFrozen: true,
    reportsJsonSafe: true,
    uiIntegration: "none",
    screenshotStatus: "not-captured-no-visual-contract"
  });
  expect(summary.policy).toMatchObject({
    policyId: "starter-ship-builder-validation-v1",
    version: 1,
    endpointRules: [{ socketType: "structural", occupancy: "Shared" }],
    requiredSocketRules: []
  });
  expect(summary.policy.signature).toBe("2553a9d1");

  const expected = {
    scout: {
      blueprintId: "blueprint_scout_v0",
      layoutHash: "fc4597b6",
      root: "scout-cockpit",
      dryMassKg: 1450,
      center: { x: 0, y: -3 / 145, z: 63 / 145 },
      minimum: { x: -2, y: -3, z: -5 },
      maximum: { x: 2, y: 2.5, z: 4.5 },
      occupied: 8,
      structureSignature: "c58b05a0",
      massSignature: "b15a294e"
    },
    cargo: {
      blueprintId: "blueprint_cargo_v0",
      layoutHash: "8613314e",
      root: "cargo-cockpit",
      dryMassKg: 2540,
      center: { x: -105 / 254, y: 0, z: 30 / 127 },
      minimum: { x: -5, y: -2.5, z: -8 },
      maximum: { x: 2.5, y: 2.5, z: 6 },
      occupied: 10,
      structureSignature: "d87d4ed6",
      massSignature: "db671981"
    },
    weapon: {
      blueprintId: "blueprint_weapon_v0",
      layoutHash: "b38b31ec",
      root: "weapon-cockpit",
      dryMassKg: 2560,
      center: { x: 3 / 128, y: 17 / 64, z: 39 / 256 },
      minimum: { x: -5, y: -2.5, z: -6 },
      maximum: { x: 5, y: 3.5, z: 5.5 },
      occupied: 11,
      structureSignature: "91b446d4",
      massSignature: "d2f9b77a"
    }
  } as const;

  expect(summary.fixtures.map((fixture) => fixture.fixture)).toEqual(["scout", "cargo", "weapon"]);
  for (const fixture of summary.fixtures) {
    const expectedFixture = expected[fixture.fixture];
    expect(fixture.blueprintId).toBe(expectedFixture.blueprintId);
    expect(fixture.layoutHash).toBe(expectedFixture.layoutHash);
    expect(fixture.structure.status).toBe("Valid");
    expect(fixture.structure.connectedComponents).toHaveLength(1);
    expect(fixture.structure.rootComponent?.rootInstanceId).toBe(expectedFixture.root);
    expect(fixture.structure.disconnectedInstanceIds).toEqual([]);
    expect(fixture.structure.unusedRequiredSocketEndpoints).toEqual([]);
    expect(fixture.structure.summary.occupiedSocketEndpointCount).toBe(expectedFixture.occupied);
    expect(fixture.structure.signature).toBe(expectedFixture.structureSignature);
    expect(fixture.mass.status).toBe("Valid");
    expect(fixture.mass.dryMassKg).toBe(expectedFixture.dryMassKg);
    expect(fixture.mass.centerOfMass?.grid.x).toBeCloseTo(expectedFixture.center.x, 12);
    expect(fixture.mass.centerOfMass?.grid.y).toBeCloseTo(expectedFixture.center.y, 12);
    expect(fixture.mass.centerOfMass?.grid.z).toBeCloseTo(expectedFixture.center.z, 12);
    expect(fixture.mass.gridBounds?.grid.minimum).toEqual(expectedFixture.minimum);
    expect(fixture.mass.gridBounds?.grid.maximum).toEqual(expectedFixture.maximum);
    expect(fixture.mass.signature).toBe(expectedFixture.massSignature);
  }
  expect(new Set(summary.fixtures.map((fixture) => fixture.structure.signature)).size).toBe(3);
  expect(new Set(summary.fixtures.map((fixture) => fixture.mass.signature)).size).toBe(3);

  await mkdir(evidenceDir, { recursive: true });
  await writeFile(summaryPath, JSON.stringify(summary, null, 2) + "\n", "utf8");
  await writeFile(markdownPath, createMarkdown(summary), "utf8");
});
