import { expect, test } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type {
  HandlingDiagnostic,
  HandlingDiagnosticsSummary,
  HandlingSuggestedFixCode,
  ShipFlightReadinessAssessments,
  ShipFlightReadinessStatus,
  ShipStats
} from "../../src/ship-builder";

type ShipBuilderDomain = typeof import("../../src/ship-builder/index");
type MutableRecord = Record<string, any>;

const evidenceDir = path.resolve(process.cwd(), "evidence");
const summaryPath = path.join(evidenceDir, "browser-ship-builder-full-stats-flight-readiness-v1-summary.json");
const markdownPath = path.join(evidenceDir, "browser-ship-builder-full-stats-flight-readiness-v1.md");

type ScenarioName = "scout" | "cargo" | "weapon" | "complete-propulsion";

interface BrowserScenarioEvidence {
  readonly scenario: ScenarioName;
  readonly blueprintId: string;
  readonly catalogSignature: string;
  readonly blueprintLayoutHash: string;
  readonly statsSignature: string;
  readonly handlingSignature: string;
  readonly readinessSignature: string;
  readonly repeatEqual: boolean;
  readonly inputUnchanged: boolean;
  readonly inputMutable: boolean;
  readonly reportsDeeplyFrozen: boolean;
  readonly reportsJsonSafe: boolean;
  readonly stats: ShipStats;
  readonly diagnostics: readonly HandlingDiagnostic[];
  readonly suggestedFixCodes: readonly HandlingSuggestedFixCode[];
  readonly diagnosticSummary: HandlingDiagnosticsSummary;
  readonly readinessStatus: ShipFlightReadinessStatus;
  readonly readiness: ShipFlightReadinessAssessments;
}

interface BrowserShipBuilderFullStatsSummary {
  readonly route: "/";
  readonly sourceModule: "/src/ship-builder/index.ts";
  readonly faviconHref: "data:,";
  readonly testBridge: {
    readonly ownPropertyAbsent: boolean;
    readonly inheritedPropertyAbsent: boolean;
    readonly bodyReferenceAbsent: boolean;
  };
  readonly starterCatalogSignature: string;
  readonly previewSignature: string;
  readonly policySignature: string;
  readonly completeCatalogInputUnchanged: boolean;
  readonly completeCatalogInputMutable: boolean;
  readonly browserErrors: {
    readonly console: 0;
    readonly requestFailed: 0;
    readonly http: 0;
  };
  readonly scenarios: readonly BrowserScenarioEvidence[];
  readonly uiIntegration: "none";
  readonly screenshotStatus: "not-captured-no-visual-contract";
  readonly nonGoals: readonly string[];
}

const createMarkdown = (summary: BrowserShipBuilderFullStatsSummary): string => {
  const tick = String.fromCharCode(96);
  const rows = summary.scenarios
    .map(
      (scenario) =>
        `| ${scenario.scenario} | ${scenario.stats.dryMassKg.value ?? "null"} | ` +
        `${scenario.stats.totalLoadedMassKg.value ?? "null"} | ${scenario.stats.deltaVMps.availability} | ` +
        `${scenario.readiness.testFlight.eligible ? "yes" : "no"} | ` +
        `${scenario.readiness.activeShip.eligible ? "yes" : "no"} | ` +
        `${tick}${scenario.statsSignature}${tick} | ${tick}${scenario.handlingSignature}${tick} | ` +
        `${tick}${scenario.readinessSignature}${tick} |`
    )
    .join("\n");

  return [
    "# Browser Ship Builder Full Stats & Flight Readiness v1 Evidence",
    "",
    "Generated by " + tick + "apps/weltraum-browser/tests/e2e/ship-builder-full-stats-flight-readiness.spec.ts" +
      tick + " through the normal-route Vite module graph.",
    "",
    "## Scenario summary",
    "",
    "| Scenario | Dry mass (kg) | Loaded mass (kg) | Delta-v availability | Test flight | Active ship | Stats | Handling | Readiness |",
    "| --- | ---: | ---: | --- | --- | --- | --- | --- | --- |",
    rows,
    "",
    "## Deterministic report payload",
    "",
    tick.repeat(3) + "json",
    JSON.stringify(summary, null, 2),
    tick.repeat(3),
    "",
    "## Guardrail confirmation",
    "",
    "- The browser loaded normal " + tick + "/" + tick + " and dynamically imported " +
      tick + "/src/ship-builder/index.ts" + tick + " through Vite.",
    "- Both own-property and prototype-chain checks proved " + tick + "window.TestBridge" +
      tick + " absent; the rendered body also contained no TestBridge reference.",
    "- Console errors, failed requests, and HTTP responses with status 400 or greater were all zero.",
    "- Every scenario was evaluated twice with byte-equivalent reports, recursively frozen output, finite JSON, and unchanged mutable caller input.",
    "- The complete-propulsion scenario uses an explicit fuel contract and publishes finite delta-v and burn time with usable RCS translation and torque.",
    "- Evidence contains no timestamp, duration, random value, absolute path, or screenshot.",
    ""
  ].join("\n");
};

test("normal browser route evaluates full ship stats and flight readiness with deterministic evidence", async ({ page }) => {
  const consoleErrors: string[] = [];
  const requestFailures: string[] = [];
  const httpErrors: string[] = [];

  page.on("console", (message) => {
    if (message.type() === "error") {
      const location = message.location();
      consoleErrors.push(`${message.text()}${location.url === "" ? "" : ` (${location.url})`}`);
    }
  });
  page.on("requestfailed", (request) => {
    requestFailures.push(`${request.method()} ${request.url()} ${request.failure()?.errorText ?? "unknown"}`);
  });
  page.on("response", (response) => {
    if (response.status() >= 400) httpErrors.push(`${response.status()} ${response.url()}`);
  });

  await page.goto("/");
  const favicon = page.locator('head link[rel="icon"]');
  await expect(favicon).toHaveCount(1);
  await expect(favicon).toHaveAttribute("href", "data:,");

  const summary = await page.evaluate<BrowserShipBuilderFullStatsSummary>(async () => {
    const sourceModule = String("/src/ship-builder/index.ts") as "/src/ship-builder/index.ts";
    const domain = (await import(/* @vite-ignore */ sourceModule)) as ShipBuilderDomain;

    const isDeeplyFrozen = (value: unknown, seen = new WeakSet<object>()): boolean => {
      if (value === null || typeof value !== "object") return true;
      if (seen.has(value)) return true;
      seen.add(value);
      if (!Object.isFrozen(value)) return false;
      return Reflect.ownKeys(value).every((key) => isDeeplyFrozen((value as Record<PropertyKey, unknown>)[key], seen));
    };
    const containsOnlyFiniteNumbers = (value: unknown): boolean => {
      if (typeof value === "number") return Number.isFinite(value);
      if (Array.isArray(value)) return value.every(containsOnlyFiniteNumbers);
      if (value !== null && typeof value === "object") return Object.values(value).every(containsOnlyFiniteNumbers);
      return true;
    };
    const jsonSafe = (value: unknown): boolean => {
      const json = JSON.stringify(value);
      return containsOnlyFiniteNumbers(value) && !/NaN|Infinity/.test(json) && JSON.stringify(JSON.parse(json)) === json;
    };

    const starterCatalog = domain.createStarterCatalog();
    const preview = domain.createShipStatPreview();
    const policy = domain.createShipAnalysisPolicy();
    const completeCatalogInput = structuredClone(
      domain.catalogDocumentForSerialization(starterCatalog)
    ) as MutableRecord;
    const completeCatalogInputBefore = JSON.stringify(completeCatalogInput);
    const engine = completeCatalogInput.partDefinitions.find(
      (part: MutableRecord) => part.partDefinitionId === domain.STARTER_PART_IDS.smallChemicalBell
    );
    if (engine === undefined) throw new Error("Synthetic complete-propulsion fixture is missing its engine definition.");
    const thruster = engine.components.find((component: MutableRecord) => component.kind === "MainThruster");
    if (thruster === undefined) throw new Error("Synthetic complete-propulsion fixture is missing its main thruster.");
    thruster.propulsionSupply = { mode: "Fuel", fuelKind: "chemical-propellant" };
    const completeCatalogPreparedInput = JSON.stringify(completeCatalogInput);
    const completeCatalog = domain.createShipPartCatalogSnapshot(completeCatalogInput);
    const completeCatalogInputUnchanged = JSON.stringify(completeCatalogInput) === completeCatalogPreparedInput;
    const completeCatalogOriginalId = completeCatalogInput.catalogId as string;
    const completeCatalogInputMutable =
      !Object.isFrozen(completeCatalogInput) &&
      Reflect.set(completeCatalogInput, "catalogId", `${completeCatalogOriginalId}-mutable`) &&
      completeCatalogInput.catalogId === `${completeCatalogOriginalId}-mutable` &&
      Reflect.set(completeCatalogInput, "catalogId", completeCatalogOriginalId) &&
      JSON.stringify(completeCatalogInput) === completeCatalogPreparedInput &&
      completeCatalogInputBefore !== completeCatalogPreparedInput;

    const inputs = [
      ["scout", domain.SCOUT_BLUEPRINT, starterCatalog],
      ["cargo", domain.CARGO_BLUEPRINT, starterCatalog],
      ["weapon", domain.WEAPON_BLUEPRINT, starterCatalog],
      ["complete-propulsion", domain.SCOUT_BLUEPRINT, completeCatalog]
    ] as const;

    const scenarios = inputs.map(([scenario, fixture, catalog]): BrowserScenarioEvidence => {
      const blueprintInput = structuredClone(fixture) as MutableRecord;
      const inputBefore = JSON.stringify(blueprintInput);
      domain.createShipBlueprint(blueprintInput, { catalog });
      const options = { preview, policy };
      const firstStats = domain.evaluateShipStats(blueprintInput, catalog, options);
      const firstHandling = domain.evaluateHandlingDiagnostics(blueprintInput, catalog, options);
      const firstReadiness = domain.evaluateShipFlightReadiness(blueprintInput, catalog, options);
      const secondStats = domain.evaluateShipStats(blueprintInput, catalog, options);
      const secondHandling = domain.evaluateHandlingDiagnostics(blueprintInput, catalog, options);
      const secondReadiness = domain.evaluateShipFlightReadiness(blueprintInput, catalog, options);
      const combinedReports = { stats: firstStats, handling: firstHandling, readiness: firstReadiness };
      const inputUnchanged = JSON.stringify(blueprintInput) === inputBefore;
      const originalBlueprintId = blueprintInput.blueprintId as string;
      const inputMutable =
        !Object.isFrozen(blueprintInput) &&
        Reflect.set(blueprintInput, "blueprintId", `${originalBlueprintId}-mutable`) &&
        blueprintInput.blueprintId === `${originalBlueprintId}-mutable` &&
        Reflect.set(blueprintInput, "blueprintId", originalBlueprintId) &&
        JSON.stringify(blueprintInput) === inputBefore;

      return {
        scenario,
        blueprintId: originalBlueprintId,
        catalogSignature: catalog.signature,
        blueprintLayoutHash: firstStats.blueprintLayoutHash,
        statsSignature: firstStats.signature,
        handlingSignature: firstHandling.signature,
        readinessSignature: firstReadiness.signature,
        repeatEqual:
          JSON.stringify(firstStats) === JSON.stringify(secondStats) &&
          JSON.stringify(firstHandling) === JSON.stringify(secondHandling) &&
          JSON.stringify(firstReadiness) === JSON.stringify(secondReadiness),
        inputUnchanged,
        inputMutable,
        reportsDeeplyFrozen:
          isDeeplyFrozen(firstStats) && isDeeplyFrozen(firstHandling) && isDeeplyFrozen(firstReadiness),
        reportsJsonSafe: jsonSafe(combinedReports),
        stats: firstStats.stats,
        diagnostics: firstHandling.diagnostics,
        suggestedFixCodes: firstHandling.suggestedFixCodes,
        diagnosticSummary: firstHandling.summary,
        readinessStatus: firstReadiness.status,
        readiness: firstReadiness.assessments
      };
    });

    const ownPropertyAbsent = !Object.prototype.hasOwnProperty.call(window, "TestBridge");
    const inheritedPropertyAbsent = !("TestBridge" in window);
    const bodyReferenceAbsent = !document.body.innerHTML.includes("TestBridge");

    return {
      route: "/",
      sourceModule,
      faviconHref: document.querySelector<HTMLLinkElement>('head link[rel="icon"]')?.getAttribute("href") as "data:,",
      testBridge: { ownPropertyAbsent, inheritedPropertyAbsent, bodyReferenceAbsent },
      starterCatalogSignature: starterCatalog.signature,
      previewSignature: preview.signature,
      policySignature: policy.signature,
      completeCatalogInputUnchanged,
      completeCatalogInputMutable,
      browserErrors: { console: 0, requestFailed: 0, http: 0 },
      scenarios,
      uiIntegration: "none",
      screenshotStatus: "not-captured-no-visual-contract",
      nonGoals: [
        "Builder UI and placement workflow",
        "flight runtime, completed test-flight state, and active-ship handoff",
        "renderer, Three.js, Combat Core, navigation, resource, and economy integration",
        "generation, cooling, power balance, and heat balance authority",
        "final balance values and player-facing diagnostic copy"
      ]
    };
  });

  expect({ consoleErrors, requestFailures, httpErrors }).toEqual({
    consoleErrors: [],
    requestFailures: [],
    httpErrors: []
  });
  expect(summary).toMatchObject({
    route: "/",
    sourceModule: "/src/ship-builder/index.ts",
    faviconHref: "data:,",
    testBridge: { ownPropertyAbsent: true, inheritedPropertyAbsent: true, bodyReferenceAbsent: true },
    starterCatalogSignature: "5aaa27fd",
    previewSignature: "b22bc0ea",
    policySignature: "22f6a341",
    completeCatalogInputUnchanged: true,
    completeCatalogInputMutable: true,
    browserErrors: { console: 0, requestFailed: 0, http: 0 },
    uiIntegration: "none",
    screenshotStatus: "not-captured-no-visual-contract"
  });
  expect(summary.scenarios.map((scenario) => scenario.scenario)).toEqual([
    "scout",
    "cargo",
    "weapon",
    "complete-propulsion"
  ]);
  expect(summary.scenarios.every((scenario) => scenario.repeatEqual)).toBe(true);
  expect(summary.scenarios.every((scenario) => scenario.inputUnchanged && scenario.inputMutable)).toBe(true);
  expect(summary.scenarios.every((scenario) => scenario.reportsDeeplyFrozen && scenario.reportsJsonSafe)).toBe(true);

  const [scout, cargo, weapon, complete] = summary.scenarios;
  expect(scout).toMatchObject({
    catalogSignature: "5aaa27fd",
    blueprintLayoutHash: "fc4597b6",
    statsSignature: "107deb2e",
    handlingSignature: "eaac5696",
    readinessSignature: "664ebe5a",
    readinessStatus: "DraftValid"
  });
  expect(scout.stats).toMatchObject({
    dryMassKg: { availability: "Available", value: 1450, unit: "kg" },
    totalLoadedMassKg: { availability: "Available", value: 1610, unit: "kg" },
    mainThrustNewtons: { availability: "Available", value: 18000, unit: "N" },
    deltaVMps: { availability: "UnavailableMissingMetadata", value: null, unit: "m/s" },
    rcsTranslationPositiveX: { availability: "Available", value: 550, unit: "N" },
    pitchTorqueNm: { availability: "Available", unit: "N*m" },
    brakingRatio: { availability: "Available", value: 0, unit: "ratio" }
  });
  expect(scout.readiness.testFlight.eligible).toBe(false);
  expect(scout.readiness.testFlight.blockingDiagnosticCodes).toContain("MissingPropulsionMetadata");

  expect(cargo).toMatchObject({
    catalogSignature: "5aaa27fd",
    blueprintLayoutHash: "8613314e",
    statsSignature: "4b0534b4",
    handlingSignature: "bfe24ebf",
    readinessSignature: "0a0c5ba9",
    readinessStatus: "DraftValid"
  });
  expect(cargo.stats).toMatchObject({
    dryMassKg: { availability: "Available", value: 2540, unit: "kg" },
    cargoMassCapacityKg: { availability: "Available", value: 1500, unit: "kg" },
    cargoVolumeCapacityM3: { availability: "Available", value: 8.5, unit: "m^3" }
  });

  expect(weapon).toMatchObject({
    catalogSignature: "5aaa27fd",
    blueprintLayoutHash: "b38b31ec",
    statsSignature: "7ad391fc",
    handlingSignature: "6b76169e",
    readinessSignature: "f9bb017f",
    readinessStatus: "DraftValid"
  });
  expect(weapon.stats).toMatchObject({
    dryMassKg: { availability: "Available", value: 2560, unit: "kg" },
    weaponCount: { availability: "Available", value: 2, unit: "count" },
    usableWeaponCount: { availability: "Available", value: 2, unit: "count" },
    fixedWeaponCount: { availability: "Available", value: 1, unit: "count" },
    turretWeaponCount: { availability: "Available", value: 1, unit: "count" },
    missingMuzzleCount: { availability: "Available", value: 0, unit: "count" }
  });

  expect(complete).toMatchObject({
    catalogSignature: "9fb36a48",
    blueprintLayoutHash: "fc4597b6",
    statsSignature: "38cf44b3",
    handlingSignature: "3acc67dd",
    readinessSignature: "bd5ded97",
    readinessStatus: "TestFlightReady"
  });
  expect(complete.stats.deltaVMps.availability).toBe("Available");
  expect(complete.stats.deltaVMps.value).toBeCloseTo((18000 / 0.35) * Math.log(1610 / 1450), 10);
  expect(complete.stats.burnTimeSeconds.availability).toBe("Available");
  expect(complete.stats.burnTimeSeconds.value).toBeCloseTo(160 / 0.35, 10);
  expect(complete.stats.rcsTranslationPositiveX.value).toBeGreaterThan(0);
  expect(
    [complete.stats.pitchTorqueNm, complete.stats.yawTorqueNm, complete.stats.rollTorqueNm].some(
      (stat) => stat.availability === "Available" && stat.value > 0
    )
  ).toBe(true);
  expect(complete.readiness.testFlight.eligible).toBe(true);
  expect(complete.readiness.activeShip.eligible).toBe(false);

  await mkdir(evidenceDir, { recursive: true });
  await writeFile(summaryPath, JSON.stringify(summary, null, 2) + "\n", "utf8");
  await writeFile(markdownPath, createMarkdown(summary), "utf8");
});
