import { expect, test } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

type ShipBuilderDomain = typeof import("../../src/ship-builder/index");

const evidenceDir = path.resolve(process.cwd(), "evidence");
const summaryPath = path.join(evidenceDir, "browser-ship-builder-domain-catalog-v1-summary.json");
const markdownPath = path.join(evidenceDir, "browser-ship-builder-domain-catalog-v1.md");

interface CategoryCount {
  readonly categoryId: string;
  readonly partCount: number;
}

interface FixtureCount {
  readonly fixture: "scout" | "cargo" | "weapon";
  readonly instanceCount: number;
  readonly connectionCount: number;
}

interface BrowserShipBuilderSummary {
  readonly route: "/";
  readonly testBridgeAbsent: boolean;
  readonly catalogSignature: string;
  readonly schemaVersions: {
    readonly catalog: number;
    readonly blueprint: number;
  };
  readonly catalogVersion: number;
  readonly categoryCount: number;
  readonly partDefinitionCount: number;
  readonly categoryCounts: readonly CategoryCount[];
  readonly scout: {
    readonly blueprintId: string;
    readonly instanceCount: number;
    readonly connectionCount: number;
    readonly canonicalRoundTripEqual: boolean;
    readonly instanceIdsStable: boolean;
    readonly connectionIdsStable: boolean;
    readonly layoutHashBefore: string;
    readonly layoutHashAfter: string;
  };
  readonly fixtureCounts: readonly FixtureCount[];
  readonly uiIntegration: "none";
  readonly screenshotStatus: "not-captured-no-visual-contract";
  readonly provisionalBalance: true;
  readonly nonGoals: readonly string[];
}

const createMarkdown = (summary: BrowserShipBuilderSummary): string => `# Browser Ship Builder Domain Catalog v1 Evidence

Generated by \`apps/weltraum-browser/tests/e2e/ship-builder-domain-catalog.spec.ts\` through a normal-route Vite module import.

## Deterministic Summary

\`\`\`json
${JSON.stringify(summary, null, 2)}
\`\`\`

## Guardrail Confirmation

- The browser loaded normal \`/\` without a query gate and \`window.TestBridge\` was absent.
- The browser context dynamically imported \`/src/ship-builder/index.ts\` through Vite; no \`main.ts\`, UI, runtime, or renderer hook was added.
- The immutable starter catalog reported ${summary.categoryCount} categories and ${summary.partDefinitionCount} parts with pinned signature \`${summary.catalogSignature}\`.
- Scout canonical serialization round-tripped byte-for-byte while stable instance IDs, connection IDs, and layout hash \`${summary.scout.layoutHashBefore}\` remained unchanged.
- Fixture shape counts are schema-integrity evidence only; they do not claim flight readiness.
- No screenshot was captured because this task has no visual contract or UI change.
- Balance metadata is provisional. Builder UI, validation/stat engines, runtime test flight, economy, and the remaining planned catalog variants are explicit non-goals.
`;

test("normal browser route dynamically imports the ship-builder domain and records deterministic evidence", async ({ page }) => {
  await page.goto("/");
  await expect.poll(() => page.evaluate(() => "TestBridge" in window)).toBe(false);

  const summary = await page.evaluate<BrowserShipBuilderSummary>(async () => {
    const testBridgeAbsent = !("TestBridge" in window);
    const modulePath = String("/src/ship-builder/index.ts");
    const domain = (await import(/* @vite-ignore */ modulePath)) as ShipBuilderDomain;
    const catalog = domain.createStarterCatalog();
    const scout = domain.SCOUT_BLUEPRINT;
    const serializedScout = domain.serializeShipBlueprint(scout);
    const parsedScout = domain.parseShipBlueprint(serializedScout, { catalog });
    const reserializedScout = domain.serializeShipBlueprint(parsedScout);

    const sortedInstanceIds = (blueprint: typeof scout): string[] =>
      blueprint.instances.map((instance) => instance.stableInstanceId).sort();
    const sortedConnectionIds = (blueprint: typeof scout): string[] =>
      blueprint.connections.map((connection) => connection.connectionId).sort();

    return {
      route: "/",
      testBridgeAbsent,
      catalogSignature: catalog.signature,
      schemaVersions: {
        catalog: catalog.schemaVersion,
        blueprint: scout.schemaVersion
      },
      catalogVersion: catalog.catalogVersion,
      categoryCount: catalog.categories.length,
      partDefinitionCount: catalog.partDefinitions.length,
      categoryCounts: catalog.categories.map((category) => ({
        categoryId: category.categoryId,
        partCount: catalog.partDefinitions.filter((part) => part.categoryId === category.categoryId).length
      })),
      scout: {
        blueprintId: scout.blueprintId,
        instanceCount: scout.instances.length,
        connectionCount: scout.connections.length,
        canonicalRoundTripEqual: serializedScout === reserializedScout,
        instanceIdsStable: JSON.stringify(sortedInstanceIds(scout)) === JSON.stringify(sortedInstanceIds(parsedScout)),
        connectionIdsStable: JSON.stringify(sortedConnectionIds(scout)) === JSON.stringify(sortedConnectionIds(parsedScout)),
        layoutHashBefore: domain.shipBlueprintLayoutHash(scout),
        layoutHashAfter: domain.shipBlueprintLayoutHash(parsedScout)
      },
      fixtureCounts: [
        {
          fixture: "scout",
          instanceCount: domain.SCOUT_BLUEPRINT.instances.length,
          connectionCount: domain.SCOUT_BLUEPRINT.connections.length
        },
        {
          fixture: "cargo",
          instanceCount: domain.CARGO_BLUEPRINT.instances.length,
          connectionCount: domain.CARGO_BLUEPRINT.connections.length
        },
        {
          fixture: "weapon",
          instanceCount: domain.WEAPON_BLUEPRINT.instances.length,
          connectionCount: domain.WEAPON_BLUEPRINT.connections.length
        }
      ],
      uiIntegration: "none",
      screenshotStatus: "not-captured-no-visual-contract",
      provisionalBalance: true,
      nonGoals: [
        "Builder UI",
        "validation and stat engines",
        "runtime test flight",
        "economy and final build costs",
        "flight-ready compatibility validation"
      ]
    };
  });

  expect(summary.testBridgeAbsent).toBe(true);
  expect(summary.categoryCount).toBe(8);
  expect(summary.partDefinitionCount).toBeGreaterThanOrEqual(16);
  expect(summary.categoryCounts).toEqual([
    { categoryId: "cockpit", partCount: 2 },
    { categoryId: "hullFrame", partCount: 2 },
    { categoryId: "mainThruster", partCount: 2 },
    { categoryId: "rcs", partCount: 2 },
    { categoryId: "fuelPower", partCount: 2 },
    { categoryId: "cargoStorage", partCount: 2 },
    { categoryId: "weapon", partCount: 2 },
    { categoryId: "utility", partCount: 2 }
  ]);
  expect(summary.catalogSignature).toBe("5aaa27fd");
  expect(summary.schemaVersions).toEqual({ catalog: 1, blueprint: 1 });
  expect(summary.catalogVersion).toBe(1);
  expect(summary.scout).toMatchObject({
    blueprintId: "blueprint_scout_v0",
    instanceCount: 5,
    connectionCount: 4,
    canonicalRoundTripEqual: true,
    instanceIdsStable: true,
    connectionIdsStable: true,
    layoutHashBefore: "fc4597b6",
    layoutHashAfter: "fc4597b6"
  });
  expect(summary.fixtureCounts).toEqual([
    { fixture: "scout", instanceCount: 5, connectionCount: 4 },
    { fixture: "cargo", instanceCount: 6, connectionCount: 5 },
    { fixture: "weapon", instanceCount: 7, connectionCount: 6 }
  ]);
  expect(summary.uiIntegration).toBe("none");
  expect(summary.screenshotStatus).toBe("not-captured-no-visual-contract");
  expect(summary.provisionalBalance).toBe(true);

  await mkdir(evidenceDir, { recursive: true });
  await writeFile(summaryPath, `${JSON.stringify(summary, null, 2)}\n`, "utf8");
  await writeFile(markdownPath, createMarkdown(summary), "utf8");
});
