import { expect, test, type Page } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

type InteractionDomain = typeof import("../../src/interaction/index");

const evidenceDir = path.resolve(process.cwd(), "evidence");
const jsonEvidencePath = path.join(evidenceDir, "browser-surface-interaction-core-v1.json");
const markdownEvidencePath = path.join(evidenceDir, "browser-surface-interaction-core-v1.md");
const generator = "apps/weltraum-browser/tests/e2e/surface-interaction-core.spec.ts";
const focusedCommand =
  "npx playwright test --config <temporary-5201-config> tests/e2e/surface-interaction-core.spec.ts";

test.use({ screenshot: "off", trace: "off" });

interface TestBridgeState {
  readonly ownProperty: boolean;
  readonly inWindow: boolean;
}

interface NormalRouteProof {
  readonly path: "/";
  readonly search: "";
  readonly testBridgeQueryPresent: false;
  readonly beforeImport: TestBridgeState;
  readonly afterImport: TestBridgeState;
}

interface InteractionScenarioRun {
  readonly modulePath: "/src/interaction/index.ts";
  readonly importedPublicApi: readonly string[];
  readonly fixture: {
    readonly actor: {
      readonly actorId: string;
      readonly revision: number;
      readonly capabilities: readonly string[];
      readonly tools: readonly string[];
      readonly energyAvailable: number;
    };
    readonly lockedCargoDoor: {
      readonly targetId: string;
      readonly revision: number;
      readonly locked: true;
      readonly requiredPermissionId: string;
      readonly supportedVerbs: readonly string[];
    };
    readonly resourceNode: {
      readonly targetId: string;
      readonly revision: number;
      readonly supportedVerbs: readonly string[];
    };
    readonly repairTerminal: {
      readonly targetId: string;
      readonly revision: number;
      readonly supportedVerbs: readonly string[];
    };
  };
  readonly decisions: {
    readonly scan: { readonly status: string; readonly reason: string | null; readonly decisionHash: string };
    readonly extract: { readonly status: string; readonly reason: string | null; readonly decisionHash: string };
    readonly repair: { readonly status: string; readonly reason: string | null; readonly decisionHash: string };
    readonly open: { readonly status: string; readonly reason: string | null; readonly decisionHash: string };
  };
  readonly hold: {
    readonly startStatus: string;
    readonly startTick: number;
    readonly requiredHoldTicks: number;
    readonly progression: readonly {
      readonly tick: number;
      readonly progressTicks: number;
      readonly readyToComplete: boolean;
    }[];
  };
  readonly staleCompletion: {
    readonly requestedTargetRevision: number;
    readonly status: string;
    readonly resultCode: string;
    readonly nextAction: string | null;
    readonly mutationIsNull: boolean;
  };
  readonly canonicalFacts: string;
  readonly proofHash: string;
}

interface InteractionBrowserEvidence {
  readonly schemaVersion: "browser-surface-interaction-core-v1";
  readonly status: "PASS";
  readonly generator: string;
  readonly scenario: "locked-door-resource-node-repair-terminal";
  readonly normalRoute: NormalRouteProof;
  readonly dynamicImport: {
    readonly modulePath: InteractionScenarioRun["modulePath"];
    readonly importedPublicApi: readonly string[];
  };
  readonly deterministicRepeat: {
    readonly canonicalFactsIdentical: true;
    readonly proofHashIdentical: true;
    readonly proofHash: string;
  };
  readonly proof: InteractionScenarioRun;
  readonly verification: {
    readonly command: string;
    readonly expectedResult: "one focused browser test passes and rewrites exactly two canonical evidence files";
    readonly observedResult: "pass";
    readonly presentationArtifact: "none: pure domain module with no visible runtime change";
  };
}

const readTestBridgeState = (page: Page): Promise<TestBridgeState> => page.evaluate(() => ({
  ownProperty: Object.prototype.hasOwnProperty.call(window, "TestBridge"),
  inWindow: "TestBridge" in window
}));

const createMarkdown = (evidence: InteractionBrowserEvidence): string => `# Browser Surface Interaction Core v1 Evidence

Generated by \`${evidence.generator}\` through the normal Browser route.

## Result

- Status: \`${evidence.status}\`
- Route: \`${evidence.normalRoute.path}${evidence.normalRoute.search}\`
- TestBridge query present: \`${evidence.normalRoute.testBridgeQueryPresent}\`
- TestBridge absent before import: \`${!evidence.normalRoute.beforeImport.ownProperty && !evidence.normalRoute.beforeImport.inWindow}\`
- TestBridge absent after import: \`${!evidence.normalRoute.afterImport.ownProperty && !evidence.normalRoute.afterImport.inWindow}\`
- Dynamic import: \`${evidence.dynamicImport.modulePath}\`
- Canonical repeated facts identical: \`${evidence.deterministicRepeat.canonicalFactsIdentical}\`
- Repeated proof hash identical: \`${evidence.deterministicRepeat.proofHashIdentical}\`
- Proof hash: \`${evidence.deterministicRepeat.proofHash}\`

## Deterministic Fixture

- Actor: \`${evidence.proof.fixture.actor.actorId}\` revision \`${evidence.proof.fixture.actor.revision}\`
- Actor capabilities: ${evidence.proof.fixture.actor.capabilities.map((value) => `\`${value}\``).join(", ")}
- Actor tools: ${evidence.proof.fixture.actor.tools.map((value) => `\`${value}\``).join(", ")}
- Locked Cargo door: \`${evidence.proof.fixture.lockedCargoDoor.targetId}\` revision \`${evidence.proof.fixture.lockedCargoDoor.revision}\`
- Resource node: \`${evidence.proof.fixture.resourceNode.targetId}\` revision \`${evidence.proof.fixture.resourceNode.revision}\`
- Repair terminal: \`${evidence.proof.fixture.repairTerminal.targetId}\` revision \`${evidence.proof.fixture.repairTerminal.revision}\`

## Decisions And Completion

| Operation | Status | Reason | Decision hash |
| --- | --- | --- | --- |
| Scan | ${evidence.proof.decisions.scan.status} | ${evidence.proof.decisions.scan.reason ?? "none"} | \`${evidence.proof.decisions.scan.decisionHash}\` |
| Extract | ${evidence.proof.decisions.extract.status} | ${evidence.proof.decisions.extract.reason ?? "none"} | \`${evidence.proof.decisions.extract.decisionHash}\` |
| Repair | ${evidence.proof.decisions.repair.status} | ${evidence.proof.decisions.repair.reason ?? "none"} | \`${evidence.proof.decisions.repair.decisionHash}\` |
| Open | ${evidence.proof.decisions.open.status} | ${evidence.proof.decisions.open.reason ?? "none"} | \`${evidence.proof.decisions.open.decisionHash}\` |

- Hold start tick: \`${evidence.proof.hold.startTick}\`
- Required hold ticks: \`${evidence.proof.hold.requiredHoldTicks}\`
- Progress: ${evidence.proof.hold.progression.map((entry) => `\`${entry.tick}:${entry.progressTicks}:${entry.readyToComplete}\``).join(", ")}
- Stale target revision requested: \`${evidence.proof.staleCompletion.requestedTargetRevision}\`
- Stale completion: \`${evidence.proof.staleCompletion.status}/${evidence.proof.staleCompletion.resultCode}\`
- Mutation returned: \`${!evidence.proof.staleCompletion.mutationIsNull}\`

## Focused Verification

- Command: \`${evidence.verification.command}\`
- Expected: ${evidence.verification.expectedResult}
- Observed: \`${evidence.verification.observedResult}\`
- Presentation artifact: ${evidence.verification.presentationArtifact}
`;

test("normal route dynamically imports and proves the surface interaction core", async ({ page }) => {
  await page.goto("/");
  await page.waitForSelector("#debug-scene", { state: "visible" });

  const routeUrl = new URL(page.url());
  expect(routeUrl.pathname).toBe("/");
  expect(routeUrl.search).toBe("");
  expect(routeUrl.searchParams.has("testBridge")).toBe(false);

  const beforeImport = await readTestBridgeState(page);
  expect(beforeImport).toEqual({ ownProperty: false, inWindow: false });

  const repeated = await page.evaluate<{
    readonly first: InteractionScenarioRun;
    readonly second: InteractionScenarioRun;
  }>(async () => {
    const modulePath = "/src/interaction/index.ts" as const;
    const interaction = (await import(/* @vite-ignore */ modulePath)) as InteractionDomain;
    const importedPublicApi = [
      "createInteractionActorContext",
      "createInteractionCandidate",
      "createInteractionRevision",
      "createInteractionTargetSnapshot",
      "createInteractionTick",
      "evaluateInteraction",
      "startInteractionSession",
      "advanceInteractionSession",
      "completeInteractionSession",
      "canonicalInteractionJson",
      "interactionHash"
    ] as const;

    for (const apiName of importedPublicApi) {
      if (typeof interaction[apiName] !== "function") {
        throw new Error(`Expected public interaction API ${apiName}.`);
      }
    }

    const runScenario = (): InteractionScenarioRun => {
      const actor = interaction.createInteractionActorContext({
        actorId: "actor.surface-technician",
        revision: 7,
        knownCapabilities: ["capability.access", "capability.extract", "capability.repair", "capability.scan"],
        capabilities: ["capability.scan", "capability.extract", "capability.access", "capability.repair"],
        tools: ["tool.scanner", "tool.cutter"],
        energyAvailable: 3,
        resources: [],
        permissions: ["permission.cargo.open"],
        legalOverride: false,
        hazardTolerance: 4,
        incapacitated: false,
        mode: "mode.surface"
      });

      const lockedCargoDoor = interaction.createInteractionTargetSnapshot({
        targetId: "target.cargo-door.locked",
        revision: 11,
        ownerId: "owner.station",
        claimId: "claim.cargo-bay",
        legalState: "Restricted",
        hazard: { level: 1, warningThreshold: 2 },
        supportedVerbs: ["Open"],
        verbRules: [{
          verb: "Open",
          requiredCapabilities: ["capability.access"],
          requiredTools: ["tool.cutter"],
          costs: { energy: 2, resources: [] },
          requiredPermissionId: "permission.cargo.open",
          requiredHoldTicks: 3,
          interruptPolicy: "Interruptible",
          movementToleranceClass: "Stationary",
          damageInterrupts: true,
          focusLossInterrupts: true,
          allowedActorModes: ["mode.surface"],
          targetBusy: false
        }]
      });

      const resourceNode = interaction.createInteractionTargetSnapshot({
        targetId: "target.resource-node.iron",
        revision: 4,
        ownerId: null,
        claimId: "claim.surface-site",
        legalState: "Legal",
        hazard: { level: 2, warningThreshold: 3 },
        supportedVerbs: ["Scan", "Extract"],
        verbRules: [{
          verb: "Scan",
          requiredCapabilities: ["capability.scan"],
          requiredTools: ["tool.scanner"],
          costs: { energy: 1, resources: [] },
          requiredPermissionId: null,
          requiredHoldTicks: 0,
          interruptPolicy: "Interruptible",
          movementToleranceClass: "Limited",
          damageInterrupts: true,
          focusLossInterrupts: true,
          allowedActorModes: ["mode.surface"],
          targetBusy: false
        }, {
          verb: "Extract",
          requiredCapabilities: ["capability.extract"],
          requiredTools: ["tool.cutter"],
          costs: { energy: 5, resources: [] },
          requiredPermissionId: null,
          requiredHoldTicks: 2,
          interruptPolicy: "Interruptible",
          movementToleranceClass: "Stationary",
          damageInterrupts: true,
          focusLossInterrupts: true,
          allowedActorModes: ["mode.surface"],
          targetBusy: false
        }]
      });

      const repairTerminal = interaction.createInteractionTargetSnapshot({
        targetId: "target.repair-terminal.alpha",
        revision: 8,
        ownerId: "owner.station",
        claimId: "claim.maintenance",
        legalState: "Legal",
        hazard: { level: 0, warningThreshold: 1 },
        supportedVerbs: ["Repair"],
        verbRules: [{
          verb: "Repair",
          requiredCapabilities: ["capability.repair"],
          requiredTools: ["tool.scanner"],
          costs: { energy: 2, resources: [] },
          requiredPermissionId: null,
          requiredHoldTicks: 1,
          interruptPolicy: "Interruptible",
          movementToleranceClass: "Stationary",
          damageInterrupts: true,
          focusLossInterrupts: true,
          allowedActorModes: ["mode.surface"],
          targetBusy: false
        }]
      });

      const candidateFor = (
        target: typeof lockedCargoDoor,
        verb: "Scan" | "Extract" | "Repair" | "Open",
        focusRank: number
      ) => interaction.createInteractionCandidate({
        actorId: actor.actorId,
        actorRevision: actor.revision,
        target,
        expectedTargetRevision: target.revision,
        verb,
        distanceMeters: 1,
        maximumDistanceMeters: 2,
        lineOfSight: true,
        reachable: true,
        focusRank
      });

      const scanDecision = interaction.evaluateInteraction(candidateFor(resourceNode, "Scan", 1), actor);
      const extractDecision = interaction.evaluateInteraction(candidateFor(resourceNode, "Extract", 1), actor);
      const repairDecision = interaction.evaluateInteraction(candidateFor(repairTerminal, "Repair", 2), actor);
      const openCandidate = candidateFor(lockedCargoDoor, "Open", 0);
      const openDecision = interaction.evaluateInteraction(openCandidate, actor);
      if (openDecision.status !== "Allowed") {
        throw new Error(`Expected Open to be allowed, received ${openDecision.status}.`);
      }

      const started = interaction.startInteractionSession({
        sessionId: "session.cargo-door.open",
        candidate: openCandidate,
        context: actor,
        decision: openDecision
      });
      if (started.status !== "Started" || started.session === null || started.progress === null) {
        throw new Error("Expected the locked Cargo door hold session to start.");
      }

      let session = started.session;
      const progression: { tick: number; progressTicks: number; readyToComplete: boolean }[] = [];
      for (const rawTick of [1, 2, 3]) {
        const advanced = interaction.advanceInteractionSession(session, {
          tick: interaction.createInteractionTick(rawTick),
          movementClass: "Stationary",
          damageOccurred: false,
          focusMaintained: true,
          modeConflict: false
        });
        if (advanced.status !== "Advanced" || advanced.session === null || advanced.progress === null) {
          throw new Error(`Expected hold progression at tick ${rawTick}.`);
        }
        session = advanced.session;
        progression.push({
          tick: advanced.progress.tick,
          progressTicks: advanced.progress.progressTicks,
          readyToComplete: advanced.progress.readyToComplete
        });
      }

      const requestedTargetRevision = interaction.createInteractionRevision(lockedCargoDoor.revision + 1);
      const staleCompletion = interaction.completeInteractionSession(session, {
        sessionId: session.sessionId,
        actorId: session.actorId,
        actorRevision: session.actorRevision,
        targetId: session.targetId,
        targetRevision: requestedTargetRevision,
        completionTick: interaction.createInteractionTick(3)
      });

      const facts = {
        modulePath,
        importedPublicApi,
        fixture: {
          actor: {
            actorId: actor.actorId,
            revision: actor.revision,
            capabilities: actor.capabilities,
            tools: actor.tools,
            energyAvailable: actor.energyAvailable
          },
          lockedCargoDoor: {
            targetId: lockedCargoDoor.targetId,
            revision: lockedCargoDoor.revision,
            locked: true as const,
            requiredPermissionId: "permission.cargo.open",
            supportedVerbs: lockedCargoDoor.supportedVerbs
          },
          resourceNode: {
            targetId: resourceNode.targetId,
            revision: resourceNode.revision,
            supportedVerbs: resourceNode.supportedVerbs
          },
          repairTerminal: {
            targetId: repairTerminal.targetId,
            revision: repairTerminal.revision,
            supportedVerbs: repairTerminal.supportedVerbs
          }
        },
        decisions: {
          scan: { status: scanDecision.status, reason: scanDecision.reason, decisionHash: scanDecision.decisionHash },
          extract: { status: extractDecision.status, reason: extractDecision.reason, decisionHash: extractDecision.decisionHash },
          repair: { status: repairDecision.status, reason: repairDecision.reason, decisionHash: repairDecision.decisionHash },
          open: { status: openDecision.status, reason: openDecision.reason, decisionHash: openDecision.decisionHash }
        },
        hold: {
          startStatus: started.status,
          startTick: started.session.startTick,
          requiredHoldTicks: started.session.requiredHoldTicks,
          progression
        },
        staleCompletion: {
          requestedTargetRevision,
          status: staleCompletion.status,
          resultCode: staleCompletion.resultCode,
          nextAction: staleCompletion.nextAction,
          mutationIsNull: staleCompletion.mutation === null
        }
      };

      return {
        ...facts,
        canonicalFacts: interaction.canonicalInteractionJson(facts),
        proofHash: interaction.interactionHash(facts)
      };
    };

    return { first: runScenario(), second: runScenario() };
  });

  const afterImport = await readTestBridgeState(page);
  expect(afterImport).toEqual({ ownProperty: false, inWindow: false });
  expect(repeated.second).toEqual(repeated.first);
  expect(repeated.second.canonicalFacts).toBe(repeated.first.canonicalFacts);
  expect(repeated.second.proofHash).toBe(repeated.first.proofHash);
  expect(repeated.first.proofHash).toBe("fnv1a32:6acc9712");

  expect(repeated.first.fixture.actor.tools).toEqual(["tool.cutter", "tool.scanner"]);
  expect(repeated.first.fixture.lockedCargoDoor).toMatchObject({ locked: true, supportedVerbs: ["Open"] });
  expect(repeated.first.fixture.resourceNode.supportedVerbs).toEqual(["Scan", "Extract"]);
  expect(repeated.first.fixture.repairTerminal.supportedVerbs).toEqual(["Repair"]);
  expect(repeated.first.decisions.scan).toMatchObject({ status: "Allowed", reason: null });
  expect(repeated.first.decisions.extract).toMatchObject({ status: "Blocked", reason: "InsufficientEnergy" });
  expect(repeated.first.decisions.repair).toMatchObject({ status: "Allowed", reason: null });
  expect(repeated.first.decisions.open).toMatchObject({ status: "Allowed", reason: null });
  expect(repeated.first.hold).toEqual({
    startStatus: "Started",
    startTick: 0,
    requiredHoldTicks: 3,
    progression: [
      { tick: 1, progressTicks: 1, readyToComplete: false },
      { tick: 2, progressTicks: 2, readyToComplete: false },
      { tick: 3, progressTicks: 3, readyToComplete: true }
    ]
  });
  expect(repeated.first.staleCompletion).toEqual({
    requestedTargetRevision: 12,
    status: "Rejected",
    resultCode: "TargetRevisionStale",
    nextAction: "RetryEvaluation",
    mutationIsNull: true
  });

  const normalRoute: NormalRouteProof = {
    path: "/",
    search: "",
    testBridgeQueryPresent: false,
    beforeImport,
    afterImport
  };
  const evidence: InteractionBrowserEvidence = {
    schemaVersion: "browser-surface-interaction-core-v1",
    status: "PASS",
    generator,
    scenario: "locked-door-resource-node-repair-terminal",
    normalRoute,
    dynamicImport: {
      modulePath: repeated.first.modulePath,
      importedPublicApi: repeated.first.importedPublicApi
    },
    deterministicRepeat: {
      canonicalFactsIdentical: true,
      proofHashIdentical: true,
      proofHash: repeated.first.proofHash
    },
    proof: repeated.first,
    verification: {
      command: focusedCommand,
      expectedResult: "one focused browser test passes and rewrites exactly two canonical evidence files",
      observedResult: "pass",
      presentationArtifact: "none: pure domain module with no visible runtime change"
    }
  };

  await mkdir(evidenceDir, { recursive: true });
  await writeFile(jsonEvidencePath, `${JSON.stringify(evidence, null, 2)}\n`, "utf8");
  await writeFile(markdownEvidencePath, createMarkdown(evidence), "utf8");
});
