import { expect, test } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { WorldStreamingScenarioResult } from "../../src/world/worldStreamingScenario";
import type { WorldStreamingTransitionEvent } from "../../src/world/worldStreaming";

const evidenceDir = path.resolve(process.cwd(), "evidence");
const summaryPath = path.join(evidenceDir, "browser-world-chunk-registry-streaming-v1-summary.json");
const markdownPath = path.join(evidenceDir, "browser-world-chunk-registry-streaming-v1.md");

const expectedChunkIds = [
  "chunk:-3:0:0",
  "chunk:-2:0:0",
  "chunk:-1:0:0",
  "chunk:0:0:0",
  "chunk:0:1:0",
  "chunk:1:0:0",
  "chunk:2:0:0",
  "chunk:3:0:0"
];

const transitionTypeOrder: Readonly<Record<WorldStreamingTransitionEvent["type"], number>> = {
  ChunkActivated: 0,
  ChunkPromotedToFull: 1,
  ChunkDemotedToSnapshot: 2,
  ChunkBecameDormant: 3,
  ChunkEnteredRenderRange: 4,
  ChunkChangedLod: 5,
  ChunkLeftRenderRange: 6
};

const rejectionReasonOrder = {
  FullChunkBudgetExceeded: 0,
  SnapshotChunkBudgetExceeded: 1,
  EstimatedEntityBudgetExceeded: 2,
  VisibleChunkBudgetExceeded: 3
} as const;

const transitionsAreOrdered = (transitions: readonly WorldStreamingTransitionEvent[]): boolean =>
  transitions.every((transition, index) => {
    if (index === 0) {
      return true;
    }
    const previous = transitions[index - 1];
    return (
      previous.chunkId < transition.chunkId ||
      (previous.chunkId === transition.chunkId && transitionTypeOrder[previous.type] <= transitionTypeOrder[transition.type])
    );
  });

const rejectionsAreOrdered = (
  rejections: WorldStreamingScenarioResult["steps"][number]["budgetSummary"]["rejections"]
): boolean =>
  rejections.every((rejection, index) => {
    if (index === 0) {
      return true;
    }
    const previous = rejections[index - 1];
    return (
      rejectionReasonOrder[previous.reason] < rejectionReasonOrder[rejection.reason] ||
      (rejectionReasonOrder[previous.reason] === rejectionReasonOrder[rejection.reason] &&
        previous.chunkId <= rejection.chunkId)
    );
  });

const createMarkdown = (result: WorldStreamingScenarioResult): string => `# Browser World Chunk Registry Streaming v1 Evidence

Generated by \`apps/weltraum-browser/tests/e2e/world-chunk-streaming.spec.ts\` through the query-gated browser TestBridge.

## Deterministic Scenario

\`\`\`json
${JSON.stringify(result, null, 2)}
\`\`\`

## Guardrail Confirmation

- Eight canonical 256 m chunks are planned from absolute world coordinates.
- Three observer steps exercise the initial baseline, a boundary crossing, and a farther move with previous-snapshot hysteresis chaining.
- Full, Snapshot, visible, and estimated-entity budgets are explicit; all downgrades remain recorded as ordered rejections.
- Floating-origin projection changes from x=0 m to x=512 m alter only the projected local observer position.
- Registry, residency, render LOD, budgets, absolute position and velocity, and streaming signatures stay invariant across the projection shift.
- \`rendererOwnsWorldTruth\` is false; the renderer is not used by this scenario.
- The companion test confirms normal \`/\` startup does not expose an own \`TestBridge\` property.
`;

test("world chunk streaming scenario is deterministic and records evidence", async ({ browser, page }) => {
  await mkdir(evidenceDir, { recursive: true });
  await page.goto("/?testBridge=1");
  await page.waitForFunction(
    () =>
      Object.prototype.hasOwnProperty.call(window, "TestBridge") &&
      typeof (window as any).TestBridge?.runWorldStreamingScenario === "function"
  );

  const repeated = await page.evaluate(() => {
    const first = (window as any).TestBridge.runWorldStreamingScenario();
    const second = (window as any).TestBridge.runWorldStreamingScenario();
    return { first, firstJson: JSON.stringify(first), secondJson: JSON.stringify(second) };
  });
  const result = repeated.first as WorldStreamingScenarioResult;

  expect(repeated.firstJson).toBe(repeated.secondJson);
  expect(result.rendererOwnsWorldTruth).toBe(false);
  expect(result.chunkSizeMeters).toBe(256);
  expect(result.registeredChunkCount).toBe(8);
  expect(result.chunkIds).toEqual(expectedChunkIds);
  expect(result.registrySignature).toMatch(/^[0-9a-f]{8}$/);
  expect(result.policySignature).toMatch(/^[0-9a-f]{8}$/);
  expect(result.policy).toEqual(
    expect.objectContaining({
      fullUpdateRadius: 64,
      snapshotRadius: 300,
      nearLodRadius: 160,
      mediumLodRadius: 400,
      farLodRadius: 700,
      simulationHysteresisMeters: 16,
      renderHysteresisMeters: 16,
      budgets: {
        maxFullChunks: 1,
        maxSnapshotChunks: 2,
        maxVisibleChunks: 7,
        maxEstimatedEntityCount: 6
      }
    })
  );

  expect(result.steps.map((step) => ({ label: step.label, position: step.observerAbsolutePosition }))).toEqual([
    { label: "initial", position: { x: 0, y: 0, z: 0 } },
    { label: "boundary", position: { x: 240, y: 0, z: 0 } },
    { label: "farther", position: { x: 520, y: 0, z: 0 } }
  ]);
  expect(result.steps.every((step) => step.registeredChunkCount === 8)).toBe(true);
  expect(result.steps.every((step) => step.registrySignature === result.registrySignature)).toBe(true);
  expect(result.steps.every((step) => step.policySignature === result.policySignature)).toBe(true);
  expect(result.steps.every((step) => step.fullChunkIds.length === 1)).toBe(true);
  expect(result.steps.every((step) => step.snapshotChunkIds.length === 2)).toBe(true);
  expect(result.steps.every((step) => step.budgetSummary.estimatedEntityCount === 6)).toBe(true);
  for (const step of result.steps) {
    expect(step.budgetSummary.fullChunkCount).toBe(step.fullChunkIds.length);
    expect(step.budgetSummary.snapshotChunkCount).toBe(step.snapshotChunkIds.length);
    expect(step.budgetSummary.visibleChunkCount).toBe(step.visibleLods.length);
    expect(step.budgetSummary.fullChunkCount).toBeLessThanOrEqual(step.budgetSummary.limits.maxFullChunks);
    expect(step.budgetSummary.snapshotChunkCount).toBeLessThanOrEqual(step.budgetSummary.limits.maxSnapshotChunks);
    expect(step.budgetSummary.visibleChunkCount).toBeLessThanOrEqual(step.budgetSummary.limits.maxVisibleChunks);
    expect(step.budgetSummary.estimatedEntityCount).toBeLessThanOrEqual(
      step.budgetSummary.limits.maxEstimatedEntityCount ?? Number.POSITIVE_INFINITY
    );
    expect(step.fullChunkIds.length + step.snapshotChunkIds.length + step.dormantChunkCount).toBe(8);
    expect(step.lodCounts).toEqual({
      Near: step.assignments.filter((assignment) => assignment.finalRenderLod === "Near").length,
      Medium: step.assignments.filter((assignment) => assignment.finalRenderLod === "Medium").length,
      Far: step.assignments.filter((assignment) => assignment.finalRenderLod === "Far").length,
      Culled: step.assignments.filter((assignment) => assignment.finalRenderLod === "Culled").length
    });
    expect(Object.values(step.lodCounts).reduce((sum, count) => sum + count, 0)).toBe(8);
    expect(rejectionsAreOrdered(step.budgetSummary.rejections)).toBe(true);
  }
  const budgetRejections = result.steps.flatMap((step) => step.budgetSummary.rejections);
  expect(budgetRejections.length).toBeGreaterThan(0);
  expect(budgetRejections.map((rejection) => rejection.reason)).toEqual(
    expect.arrayContaining(["SnapshotChunkBudgetExceeded", "VisibleChunkBudgetExceeded"])
  );
  expect(result.steps[0].transitions).toEqual([]);
  expect(result.steps[1].transitions.length).toBeGreaterThan(0);
  expect(result.steps[2].transitions.length).toBeGreaterThan(0);
  expect(result.steps.every((step) => transitionsAreOrdered(step.transitions))).toBe(true);
  expect(result.steps.every((step) => JSON.parse(step.canonicalSerializedSnapshot).signature === step.signature)).toBe(true);

  expect(result.floatingOrigin.before.originAbsolutePosition).toEqual({ x: 0, y: 0, z: 0 });
  expect(result.floatingOrigin.after.originAbsolutePosition).toEqual({ x: 512, y: 0, z: 0 });
  expect(result.floatingOrigin.before.projectedLocalPosition).toEqual({ x: 520, y: 0, z: 0 });
  expect(result.floatingOrigin.after.projectedLocalPosition).toEqual({ x: 8, y: 0, z: 0 });
  expect(result.floatingOrigin.before.absoluteVelocity).toEqual({ x: 12, y: 0, z: -3 });
  expect(result.floatingOrigin.after.absoluteVelocity).toEqual({ x: 12, y: 0, z: -3 });
  expect(result.floatingOrigin.before.chunkIds).toEqual(expectedChunkIds);
  expect(result.floatingOrigin.after.chunkIds).toEqual(expectedChunkIds);
  expect(result.floatingOrigin.before.assignments).toEqual(result.floatingOrigin.after.assignments);
  expect(Object.values(result.floatingOrigin.invariants).every(Boolean)).toBe(true);

  const normalContext = await browser.newContext();
  const normalPage = await normalContext.newPage();
  await normalPage.goto("/");
  await normalPage.waitForLoadState("load");
  await expect
    .poll(() => normalPage.evaluate(() => Object.prototype.hasOwnProperty.call(window, "TestBridge")))
    .toBe(false);
  await normalContext.close();

  await writeFile(summaryPath, JSON.stringify(result, null, 2), "utf8");
  await writeFile(markdownPath, createMarkdown(result), "utf8");
});

test("normal browser startup keeps TestBridge hidden", async ({ page }) => {
  await page.goto("/");
  await page.waitForLoadState("load");
  await expect
    .poll(() => page.evaluate(() => Object.prototype.hasOwnProperty.call(window, "TestBridge")))
    .toBe(false);
});
